//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class UIImage;

@interface _SplashView : UIView
{
    UIImage *_maskImage;	// 8 = 0x8
}

- (void).cxx_destruct;	// IMP=0x000000010005a134
- (id)initWithFrame:(struct CGRect)arg1 style:(long long)arg2 templateImage:(id)arg3;	// IMP=0x0000000100059bd8

@end

