//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSOperationQueue, PBAccessoryUpdateOperation, TVSBackgroundTask;

@interface PBAccessoryUpdateService : NSObject
{
    unsigned int _powerAssertion;	// 8 = 0x8
    _Bool _monitoringStarted;	// 12 = 0xc
    _Bool _manualUpdateInProgress;	// 13 = 0xd
    TVSBackgroundTask *_accessoryUpdateCheckTask;	// 16 = 0x10
    PBAccessoryUpdateOperation *_currentOperation;	// 24 = 0x18
    NSOperationQueue *_operationQueue;	// 32 = 0x20
}

+ (id)sharedInstance;	// IMP=0x000000010008b134
@property(nonatomic, getter=isManualUpdateInProgress) _Bool manualUpdateInProgress; // @synthesize manualUpdateInProgress=_manualUpdateInProgress;
@property(readonly, nonatomic) NSOperationQueue *operationQueue; // @synthesize operationQueue=_operationQueue;
@property(retain, nonatomic) PBAccessoryUpdateOperation *currentOperation; // @synthesize currentOperation=_currentOperation;
@property(retain, nonatomic) TVSBackgroundTask *accessoryUpdateCheckTask; // @synthesize accessoryUpdateCheckTask=_accessoryUpdateCheckTask;
- (void).cxx_destruct;	// IMP=0x000000010008d424
- (void)_releasePowerAssertion;	// IMP=0x000000010008d17c
- (void)_holdPowerAssertion;	// IMP=0x000000010008cec8
- (void)_operationDidComplete:(id)arg1;	// IMP=0x000000010008c940
- (void)_startImmediateBluetoothRemoteUpdate;	// IMP=0x000000010008c348
- (void)_reallyScheduleBluetoothRemoteUpdateWithInterval:(double)arg1 delay:(double)arg2;	// IMP=0x000000010008bc58
- (void)_scheduleBluetoothRemoteUpdate;	// IMP=0x000000010008b7d0
- (_Bool)canDeferFirmwareUpdate;	// IMP=0x000000010008b5b8
- (void)startManualBluetoothRemoteUpdate;	// IMP=0x000000010008b4a0
- (void)startBluetoothUpdateMonitoring;	// IMP=0x000000010008b24c

@end

