//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UICollectionViewFlowLayout.h"

@class NSArray, NSIndexPath;

@interface PBAppSwitcherLayout : UICollectionViewFlowLayout
{
    _Bool _transitioningIn;	// 8 = 0x8
    _Bool _transitioningOut;	// 9 = 0x9
    struct CGRect _newLayoutSelectedItemFrame;	// 16 = 0x10
    struct CGRect _oldLayoutSelectedItemFrame;	// 48 = 0x30
    NSIndexPath *_previousSelectedIndexPath;	// 80 = 0x50
    NSArray *_iconIndexPathsToDelete;	// 88 = 0x58
    NSArray *_iconIndexPathsToInsert;	// 96 = 0x60
    NSIndexPath *_selectedIndexPath;	// 104 = 0x68
    struct CGRect _focusedIconViewFrame;	// 112 = 0x70
}

+ (struct CGSize)viewportSize;	// IMP=0x0000000100048fdc
+ (struct CGSize)focusableSize;	// IMP=0x0000000100048fcc
+ (struct CGSize)focusedSize;	// IMP=0x0000000100048fb8
+ (struct CGSize)unfocusedSize;	// IMP=0x0000000100048f78
@property(nonatomic) struct CGRect focusedIconViewFrame; // @synthesize focusedIconViewFrame=_focusedIconViewFrame;
@property(copy, nonatomic) NSIndexPath *selectedIndexPath; // @synthesize selectedIndexPath=_selectedIndexPath;
- (void).cxx_destruct;	// IMP=0x000000010004a3dc
- (void)_adjustSupplementaryViewTransitionAttributes:(id)arg1 atIndexPath:(id)arg2;	// IMP=0x000000010004a1c8
- (void)_adjustSupplementaryViewAttributes:(id)arg1 atIndexPath:(id)arg2 forSelectedIndexPath:(id)arg3;	// IMP=0x0000000100049fe0
- (id)finalLayoutAttributesForDisappearingSupplementaryElementOfKind:(id)arg1 atIndexPath:(id)arg2;	// IMP=0x0000000100049e30
- (id)initialLayoutAttributesForAppearingSupplementaryElementOfKind:(id)arg1 atIndexPath:(id)arg2;	// IMP=0x0000000100049d14
- (id)layoutAttributesForSupplementaryViewOfKind:(id)arg1 atIndexPath:(id)arg2;	// IMP=0x0000000100049c78
- (id)indexPathsToDeleteForSupplementaryViewOfKind:(id)arg1;	// IMP=0x0000000100049c24
- (id)indexPathsToInsertForSupplementaryViewOfKind:(id)arg1;	// IMP=0x0000000100049bd0
- (void)finalizeCollectionViewUpdates;	// IMP=0x0000000100049b64
- (void)prepareForCollectionViewUpdates:(id)arg1;	// IMP=0x00000001000497c0
- (void)prepareForTransitionToLayout:(id)arg1;	// IMP=0x0000000100049708
- (void)prepareForTransitionFromLayout:(id)arg1;	// IMP=0x000000010004968c
- (void)finalizeLayoutTransition;	// IMP=0x0000000100049670
- (id)layoutAttributesForElementsInRect:(struct CGRect)arg1;	// IMP=0x0000000100049420
- (_Bool)shouldInvalidateLayoutForBoundsChange:(struct CGRect)arg1;	// IMP=0x0000000100049418
- (struct CGPoint)targetContentOffsetForProposedContentOffset:(struct CGPoint)arg1;	// IMP=0x0000000100049354
- (id)init;	// IMP=0x0000000100049040

@end

