//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class LSApplicationProxy, NSHashTable, NSString, PBAppSwitcherManager, PBSAppState, UIImage;

@interface PBAppSwitcherItem : NSObject
{
    NSHashTable *_observers;	// 8 = 0x8
    _Bool _live;	// 16 = 0x10
    _Bool _cacheDeleting;	// 17 = 0x11
    long long _itemType;	// 24 = 0x18
    LSApplicationProxy *_applicationProxy;	// 32 = 0x20
    PBAppSwitcherManager *_manager;	// 40 = 0x28
    PBSAppState *_appState;	// 48 = 0x30
}

@property(copy, nonatomic) PBSAppState *appState; // @synthesize appState=_appState;
@property(readonly, nonatomic) __weak PBAppSwitcherManager *manager; // @synthesize manager=_manager;
@property(nonatomic, getter=isCacheDeleting) _Bool cacheDeleting; // @synthesize cacheDeleting=_cacheDeleting;
@property(readonly, nonatomic, getter=isLive) _Bool live; // @synthesize live=_live;
@property(retain, nonatomic) LSApplicationProxy *applicationProxy; // @synthesize applicationProxy=_applicationProxy;
@property(readonly, nonatomic) long long itemType; // @synthesize itemType=_itemType;
- (void).cxx_destruct;	// IMP=0x000000010009041c
- (void)_updateForProgressChange;	// IMP=0x0000000100090378
- (void)_notifyCacheDeletingDidChange;	// IMP=0x0000000100090200
- (void)_notifyIconDidChange;	// IMP=0x00000001000900b0
- (void)_notifyDisplayNameDidChange;	// IMP=0x000000010008ff60
- (void)_notifyInstallStateDidChange;	// IMP=0x000000010008fe10
@property(readonly, nonatomic) UIImage *iconImage;
@property(readonly, copy, nonatomic) NSString *localizedName;
@property(readonly, copy, nonatomic) NSString *identifier;
- (void)removeObserver:(id)arg1;	// IMP=0x000000010008fb4c
- (void)addObserver:(id)arg1;	// IMP=0x000000010008fb2c
- (id)initWithType:(long long)arg1 proxy:(id)arg2 appState:(id)arg3 manager:(id)arg4 live:(_Bool)arg5;	// IMP=0x000000010008f9bc

@end

