//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "LSApplicationWorkspaceObserverProtocol.h"

@class NSArray, NSDictionary, NSString, PBAppSwitcherItem;

@interface PBAppSwitcherManager : NSObject <LSApplicationWorkspaceObserverProtocol>
{
    NSArray *_activeItems;	// 8 = 0x8
    PBAppSwitcherItem *_focusedProcessItem;	// 16 = 0x10
    PBAppSwitcherItem *_mainMenuItem;	// 24 = 0x18
    NSString *_focusedProcessBundleID;	// 32 = 0x20
    PBAppSwitcherItem *_airPlayItem;	// 40 = 0x28
    NSDictionary *_applicationIdentifierToAppState;	// 48 = 0x30
}

+ (id)_applicationIdentifierToAppProxyDictionaryFromProxies:(id)arg1;	// IMP=0x0000000100044224
+ (_Bool)canKillItem:(id)arg1;	// IMP=0x0000000100042594
+ (_Bool)canSwitchToItem:(id)arg1;	// IMP=0x0000000100042490
+ (_Bool)shouldActivateForProcessWithIdentifier:(id)arg1;	// IMP=0x00000001000422b4
@property(copy, nonatomic) NSDictionary *applicationIdentifierToAppState; // @synthesize applicationIdentifierToAppState=_applicationIdentifierToAppState;
@property(retain, nonatomic) PBAppSwitcherItem *airPlayItem; // @synthesize airPlayItem=_airPlayItem;
@property(readonly, copy, nonatomic) NSString *focusedProcessBundleID; // @synthesize focusedProcessBundleID=_focusedProcessBundleID;
- (void).cxx_destruct;	// IMP=0x0000000100044444
- (void)_updateItemsInstallProgressWithProxyMap:(id)arg1;	// IMP=0x000000010004408c
- (void)_updateWithRemovedItems:(id)arg1;	// IMP=0x0000000100043e8c
- (void)_updateItemsWithUninstalledProxyMap:(id)arg1;	// IMP=0x0000000100043cac
- (void)_updateItemsWithInstalledProxyMap:(id)arg1;	// IMP=0x0000000100043b0c
- (void)_updateItemsWithApplicationState;	// IMP=0x00000001000438d4
- (void)_appDepotAppStateDidChangeNotification:(id)arg1;	// IMP=0x00000001000437f0
- (void)applicationInstallsDidChange:(id)arg1;	// IMP=0x00000001000436ac
- (void)applicationsDidUninstall:(id)arg1;	// IMP=0x0000000100043568
- (void)applicationsDidInstall:(id)arg1;	// IMP=0x0000000100043424
- (void)killProcess:(id)arg1;	// IMP=0x000000010004330c
- (void)activateApplication:(id)arg1 withCompletion:(CDUnknownBlockType)arg2;	// IMP=0x00000001000431d4
- (id)addItemWithIdentifier:(id)arg1;	// IMP=0x000000010004307c
@property(readonly, nonatomic) NSArray *activeItems; // @synthesize activeItems=_activeItems;
@property(readonly, nonatomic) PBAppSwitcherItem *focusedProcessItem; // @synthesize focusedProcessItem=_focusedProcessItem;
@property(readonly, nonatomic) PBAppSwitcherItem *mainMenuItem; // @synthesize mainMenuItem=_mainMenuItem;
- (void)dealloc;	// IMP=0x0000000100042870
- (id)initWithFocusedProcessBundleID:(id)arg1;	// IMP=0x00000001000426a8
- (id)init;	// IMP=0x0000000100042698

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

