//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class PBAppSwitcherCollectionViewCell;

@protocol PBAppSwitcherCollectionViewCellDelegate <NSObject>
- (void)collectionViewCellDidRequestDelete:(PBAppSwitcherCollectionViewCell *)arg1;
- (void)collectionViewCellDidEndDeleteGesture:(PBAppSwitcherCollectionViewCell *)arg1;
- (void)collectionViewCellDidBeginDeleteGesture:(PBAppSwitcherCollectionViewCell *)arg1;

@optional
- (_Bool)collectionViewCellCanRequestDelete:(PBAppSwitcherCollectionViewCell *)arg1;
@end

