//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "PBAppSwitcherCollectionViewCellDelegate.h"
#import "UICollectionViewDataSource.h"
#import "UICollectionViewDelegate.h"

@class NSMutableArray, NSString, PBAppSwitcherFullscreenLayout, PBAppSwitcherItem, PBAppSwitcherLayout, PBAppSwitcherManager, TVSStateMachine, _PBAppSwitcherCollectionView;

@interface PBAppSwitcherCollectionViewController : UIViewController <UICollectionViewDelegate, UICollectionViewDataSource, PBAppSwitcherCollectionViewCellDelegate>
{
    _Bool _firstFocusMove;	// 8 = 0x8
    _Bool _inDeleteGesture;	// 9 = 0x9
    id <PBAppSwitcherCollectionViewControllerDelegate> _delegate;	// 16 = 0x10
    PBAppSwitcherItem *_itemBeingInserted;	// 24 = 0x18
    PBAppSwitcherItem *_itemToTransition;	// 32 = 0x20
    PBAppSwitcherManager *_manager;	// 40 = 0x28
    PBAppSwitcherLayout *_switcherLayout;	// 48 = 0x30
    PBAppSwitcherFullscreenLayout *_fullscreenLayout;	// 56 = 0x38
    _PBAppSwitcherCollectionView *_collectionView;	// 64 = 0x40
    NSMutableArray *_items;	// 72 = 0x48
    TVSStateMachine *_stateMachine;	// 80 = 0x50
}

@property(retain, nonatomic) TVSStateMachine *stateMachine; // @synthesize stateMachine=_stateMachine;
@property(copy, nonatomic) NSMutableArray *items; // @synthesize items=_items;
@property(retain, nonatomic) _PBAppSwitcherCollectionView *collectionView; // @synthesize collectionView=_collectionView;
@property(retain, nonatomic) PBAppSwitcherFullscreenLayout *fullscreenLayout; // @synthesize fullscreenLayout=_fullscreenLayout;
@property(retain, nonatomic) PBAppSwitcherLayout *switcherLayout; // @synthesize switcherLayout=_switcherLayout;
@property(retain, nonatomic) PBAppSwitcherManager *manager; // @synthesize manager=_manager;
@property(retain, nonatomic) PBAppSwitcherItem *itemToTransition; // @synthesize itemToTransition=_itemToTransition;
@property(retain, nonatomic) PBAppSwitcherItem *itemBeingInserted; // @synthesize itemBeingInserted=_itemBeingInserted;
@property(nonatomic) _Bool inDeleteGesture; // @synthesize inDeleteGesture=_inDeleteGesture;
@property(nonatomic) _Bool firstFocusMove; // @synthesize firstFocusMove=_firstFocusMove;
@property(nonatomic) __weak id <PBAppSwitcherCollectionViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;	// IMP=0x000000010003c67c
- (id)_indexPathForItem:(id)arg1;	// IMP=0x000000010003c390
- (id)_itemForCell:(id)arg1;	// IMP=0x000000010003c2cc
- (id)_selectedIndexPath;	// IMP=0x000000010003c238
- (void)_setSelectedIndexPath:(id)arg1;	// IMP=0x000000010003c1a0
- (void)_configureInitialSelection;	// IMP=0x000000010003c040
- (id)cellForItemAtIndex:(unsigned long long)arg1;	// IMP=0x000000010003bfcc
- (_Bool)_removeItem:(id)arg1 userKilled:(_Bool)arg2;	// IMP=0x000000010003bb28
- (id)_exitToItem:(id)arg1;	// IMP=0x000000010003aa30
- (id)_checkForPendingTransitions;	// IMP=0x000000010003a99c
- (id)_activateItem:(id)arg1;	// IMP=0x000000010003a77c
- (void)_updateForSwitcherVisible;	// IMP=0x000000010003a770
- (void)_showAppSwitcher;	// IMP=0x000000010003a104
- (void)_initializeStateMachine;	// IMP=0x0000000100038ef0
- (void)_itemRemoved:(id)arg1;	// IMP=0x0000000100038dc8
- (void)_focusGestureDidBeginNotification:(id)arg1;	// IMP=0x0000000100038db4
- (void)collectionViewCellDidRequestDelete:(id)arg1;	// IMP=0x0000000100038cdc
- (_Bool)collectionViewCellCanRequestDelete:(id)arg1;	// IMP=0x0000000100038bc4
- (void)collectionViewCellDidEndDeleteGesture:(id)arg1;	// IMP=0x0000000100038bb4
- (void)collectionViewCellDidBeginDeleteGesture:(id)arg1;	// IMP=0x0000000100038ba0
- (void)collectionView:(id)arg1 didSelectItemAtIndexPath:(id)arg2;	// IMP=0x0000000100038b14
- (_Bool)collectionView:(id)arg1 canFocusItemAtIndexPath:(id)arg2;	// IMP=0x00000001000389cc
- (void)collectionView:(id)arg1 didUpdateFocusInContext:(id)arg2 withAnimationCoordinator:(id)arg3;	// IMP=0x0000000100038554
- (void)collectionView:(id)arg1 willDisplaySupplementaryView:(id)arg2 forElementKind:(id)arg3 atIndexPath:(id)arg4;	// IMP=0x0000000100038478
- (id)collectionView:(id)arg1 viewForSupplementaryElementOfKind:(id)arg2 atIndexPath:(id)arg3;	// IMP=0x0000000100038368
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;	// IMP=0x00000001000380d8
- (long long)collectionView:(id)arg1 numberOfItemsInSection:(long long)arg2;	// IMP=0x00000001000380c0
- (void)_handleButtonGesture:(id)arg1;	// IMP=0x0000000100038050
- (void)_postActivateItem:(id)arg1;	// IMP=0x0000000100037f78
- (void)_postExitWithItem:(id)arg1;	// IMP=0x0000000100037ea0
- (void)openApplicationWithIdentifier:(id)arg1;	// IMP=0x0000000100037cdc
- (void)exitToCurrentApplication;	// IMP=0x0000000100037c34
- (id)indexPathForPreferredFocusedViewInCollectionView:(id)arg1;	// IMP=0x0000000100037b44
- (id)preferredFocusedView;	// IMP=0x0000000100037b34
- (id)collectionViewLayout;	// IMP=0x0000000100037ae0
- (void)viewDidLayoutSubviews;	// IMP=0x00000001000379c0
- (void)viewDidAppear:(_Bool)arg1;	// IMP=0x000000010003795c
- (void)viewWillAppear:(_Bool)arg1;	// IMP=0x0000000100037878
- (void)viewDidLoad;	// IMP=0x0000000100037488
- (void)dealloc;	// IMP=0x000000010003740c
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;	// IMP=0x00000001000371b8

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

