//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface PBAppSwitcherSnapshotUtilities : NSObject
{
}

+ (void)updateSnapshot:(id)arg1 forProcessWithIdentifier:(id)arg2;	// IMP=0x0000000100080f38
+ (id)snapshotWithScene:(id)arg1 context:(id)arg2 error:(long long *)arg3;	// IMP=0x0000000100080b70
+ (id)sceneForProcessWithIdentifier:(id)arg1;	// IMP=0x0000000100080a9c
+ (id)snapshotViewForProcessWithIdentifier:(id)arg1;	// IMP=0x000000010008087c

@end

