//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class PBAppSwitcherItem;

@protocol PBAppSwitcherItemObserver <NSObject>

@optional
- (void)cacheDeletingDidChange:(PBAppSwitcherItem *)arg1;
- (void)appIconDidChange:(PBAppSwitcherItem *)arg1;
- (void)displayNameDidChange:(PBAppSwitcherItem *)arg1;
- (void)installStateDidChange:(PBAppSwitcherItem *)arg1;
@end

