//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UICollectionReusableView.h"

#import "PBAppSwitcherItemObserver.h"
#import "SBIconProgressViewDelegate.h"

@class NSString, PBAppSwitcherItem, SBIconProgressView, TVVibrantLabel, UIImage, UIImageView, UIView, _TVMusicBarsView;

@interface PBAppSwitcherIconView : UICollectionReusableView <SBIconProgressViewDelegate, PBAppSwitcherItemObserver>
{
    _Bool _pendingProgressViewUpdate;	// 8 = 0x8
    _Bool _useFocusedAppearance;	// 9 = 0x9
    _Bool _appIsNowPlaying;	// 10 = 0xa
    PBAppSwitcherItem *_item;	// 16 = 0x10
    TVVibrantLabel *_titleLabel;	// 24 = 0x18
    UIImageView *_iconView;	// 32 = 0x20
    _TVMusicBarsView *_musicBarsView;	// 40 = 0x28
    SBIconProgressView *_progressView;	// 48 = 0x30
    NSString *_title;	// 56 = 0x38
    UIImage *_image;	// 64 = 0x40
    UIView *_cacheDeleteOverlay;	// 72 = 0x48
}

@property(retain, nonatomic) UIView *cacheDeleteOverlay; // @synthesize cacheDeleteOverlay=_cacheDeleteOverlay;
@property(retain, nonatomic) UIImage *image; // @synthesize image=_image;
@property(retain, nonatomic) NSString *title; // @synthesize title=_title;
@property(retain, nonatomic) SBIconProgressView *progressView; // @synthesize progressView=_progressView;
@property(nonatomic) _Bool appIsNowPlaying; // @synthesize appIsNowPlaying=_appIsNowPlaying;
@property(retain, nonatomic) _TVMusicBarsView *musicBarsView; // @synthesize musicBarsView=_musicBarsView;
@property(retain, nonatomic) UIImageView *iconView; // @synthesize iconView=_iconView;
@property(retain, nonatomic) TVVibrantLabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(retain, nonatomic) PBAppSwitcherItem *item; // @synthesize item=_item;
@property(nonatomic) _Bool useFocusedAppearance; // @synthesize useFocusedAppearance=_useFocusedAppearance;
- (void).cxx_destruct;	// IMP=0x000000010009cc60
- (void)progressViewCanBeRemoved:(id)arg1;	// IMP=0x000000010009ca9c
- (void)_removeProgressView;	// IMP=0x000000010009ca40
- (void)_updateProgressView;	// IMP=0x000000010009c7bc
- (id)_progressMaskImage;	// IMP=0x000000010009c6f0
- (void)_setNeedsProgressViewUpdate;	// IMP=0x000000010009c644
- (void)_updateCacheDeleteStyle;	// IMP=0x000000010009c640
- (void)_updateImage;	// IMP=0x000000010009c5cc
- (void)_updateTitle;	// IMP=0x000000010009c558
- (void)cacheDeletingDidChange:(id)arg1;	// IMP=0x000000010009c1f0
- (void)appIconDidChange:(id)arg1;	// IMP=0x000000010009c1e4
- (void)displayNameDidChange:(id)arg1;	// IMP=0x000000010009c1d8
- (void)installStateDidChange:(id)arg1;	// IMP=0x000000010009c1cc
- (void)_manageNowPlayingFlag;	// IMP=0x000000010009c04c
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;	// IMP=0x000000010009bf10
- (void)layoutSubviews;	// IMP=0x000000010009bcec
- (void)prepareForReuse;	// IMP=0x000000010009bc14
- (void)dealloc;	// IMP=0x000000010009bb6c
- (id)initWithFrame:(struct CGRect)arg1;	// IMP=0x000000010009b97c

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

