//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "FBSystemApp.h"

#import "FBSceneManagerDelegate.h"
#import "FBSceneManagerObserver.h"
#import "PBSBulletinServiceDelegate.h"

@class NSMutableDictionary, NSMutableSet, NSString, NSTimer, PBBulletinService, PBSBulletin, TVSUserActivityTrigger;

@interface PBApplication : FBSystemApp <FBSceneManagerDelegate, FBSceneManagerObserver, PBSBulletinServiceDelegate>
{
    PBBulletinService *_bulletinService;	// 8 = 0x8
    PBSBulletin *_networkBulletin;	// 16 = 0x10
    NSMutableSet *_clientsWantingIdleTimerDisabled;	// 24 = 0x18
    _Bool _needsAdjustToDisplayChange;	// 32 = 0x20
    _Bool _needsUpdateActivityTriggersAndBackgroundTasks;	// 33 = 0x21
    _Bool _inhibitScreenSaver;	// 34 = 0x22
    _Bool _preparingSyntheticButtonEvent;	// 35 = 0x23
    _Bool _airPlayActive;	// 36 = 0x24
    NSTimer *_bluetoothRemoteKeepAliveTimer;	// 40 = 0x28
    TVSUserActivityTrigger *_remotePresenceDetectionTrigger;	// 48 = 0x30
    TVSUserActivityTrigger *_hiliteModeTrigger;	// 56 = 0x38
    TVSUserActivityTrigger *_screenSaverTrigger;	// 64 = 0x40
    TVSUserActivityTrigger *_sleepTrigger;	// 72 = 0x48
    TVSUserActivityTrigger *_bluetoothRemoteSleepTrigger;	// 80 = 0x50
    TVSUserActivityTrigger *_idleTypeBackgroundTasksTrigger;	// 88 = 0x58
    NSMutableDictionary *_appActivateInfoByBundleIdentifier;	// 96 = 0x60
}

+ (id)sharedApplication;	// IMP=0x00000001000049d4
@property(retain, nonatomic) NSMutableDictionary *appActivateInfoByBundleIdentifier; // @synthesize appActivateInfoByBundleIdentifier=_appActivateInfoByBundleIdentifier;
@property(retain, nonatomic) TVSUserActivityTrigger *idleTypeBackgroundTasksTrigger; // @synthesize idleTypeBackgroundTasksTrigger=_idleTypeBackgroundTasksTrigger;
@property(retain, nonatomic) TVSUserActivityTrigger *bluetoothRemoteSleepTrigger; // @synthesize bluetoothRemoteSleepTrigger=_bluetoothRemoteSleepTrigger;
@property(retain, nonatomic) TVSUserActivityTrigger *sleepTrigger; // @synthesize sleepTrigger=_sleepTrigger;
@property(retain, nonatomic) TVSUserActivityTrigger *screenSaverTrigger; // @synthesize screenSaverTrigger=_screenSaverTrigger;
@property(retain, nonatomic) TVSUserActivityTrigger *hiliteModeTrigger; // @synthesize hiliteModeTrigger=_hiliteModeTrigger;
@property(retain, nonatomic) TVSUserActivityTrigger *remotePresenceDetectionTrigger; // @synthesize remotePresenceDetectionTrigger=_remotePresenceDetectionTrigger;
@property(retain, nonatomic) NSTimer *bluetoothRemoteKeepAliveTimer; // @synthesize bluetoothRemoteKeepAliveTimer=_bluetoothRemoteKeepAliveTimer;
@property(nonatomic) _Bool airPlayActive; // @synthesize airPlayActive=_airPlayActive;
- (void).cxx_destruct;	// IMP=0x000000010000bfd4
- (void)activateAppSwitcher;	// IMP=0x000000010000bd2c
- (id)appSwitcherWindow;	// IMP=0x000000010000bcb0
- (void)bulletinService:(id)arg1 didDismissBulletin:(id)arg2 withReason:(unsigned long long)arg3;	// IMP=0x000000010000bc3c
- (id)sceneManager:(id)arg1 createDefaultTransitionContextForScene:(id)arg2;	// IMP=0x000000010000bbac
- (void)sceneManager:(id)arg1 scene:(id)arg2 didUpdateClientSettingsWithDiff:(id)arg3 oldClientSettings:(id)arg4 transitionContext:(id)arg5;	// IMP=0x000000010000b9f8
- (void)sceneManager:(id)arg1 scene:(id)arg2 didReceiveActions:(id)arg3;	// IMP=0x000000010000b3f0
- (void)handleAppTransition:(id)arg1;	// IMP=0x000000010000b380
- (id)_sanitizeAppIdentifierHistory:(id)arg1;	// IMP=0x000000010000b1c4
- (void)_activateAppIdleAction:(id)arg1;	// IMP=0x000000010000af6c
- (_Bool)_focusedSceneHasHiliteModeEnabled;	// IMP=0x000000010000ad80
- (void)_updateHiliteModeState;	// IMP=0x000000010000ac68
- (void)_deactivateScreenSaver;	// IMP=0x000000010000abe4
- (void)_activateScreenSaverFromUserAction:(_Bool)arg1;	// IMP=0x000000010000ab40
- (void)_saveRecentApplicationBundleIdentifiers;	// IMP=0x000000010000aaa0
- (void)setNeedsUpdateActivityTriggersAndBackgroundTasks;	// IMP=0x000000010000a9d4
- (void)_updateBackgroundTaskScheduling;	// IMP=0x000000010000a614
- (void)_updateUserActivityTriggers;	// IMP=0x00000001000099b4
- (void)_updateLastKnownGoodTimestamp;	// IMP=0x00000001000091fc
- (void)_setTimeFromLastKnownGoodTimestamp;	// IMP=0x0000000100008edc
- (void)_startCoreControlManagement;	// IMP=0x0000000100008df4
- (void)client:(id)arg1 setIgnoresAvailableDisplayModesChanges:(_Bool)arg2;	// IMP=0x0000000100008d94
- (void)cancelScheduledActivationForAppWithBundleIdentifier:(id)arg1;	// IMP=0x0000000100008bdc
- (void)activateAppIfPlayingMusicAfterIdleTime:(double)arg1 bundleIdentifier:(id)arg2 openURL:(id)arg3;	// IMP=0x0000000100008968
- (void)forwardMenuButtonEvent;	// IMP=0x00000001000088f8
- (void)sendMenuButtonEventRequestedByClient:(id)arg1;	// IMP=0x000000010000878c
- (void)deactivateScreenSaverRequestedByClient:(id)arg1;	// IMP=0x0000000100008660
- (void)activateScreenSaverRequestedByClient:(id)arg1;	// IMP=0x0000000100008530
- (void)rebootRequestedByClient:(id)arg1;	// IMP=0x00000001000083ec
- (void)relaunchRequestedByClient:(id)arg1;	// IMP=0x00000001000082a8
- (void)relaunchBackboarddRequestedByClient:(id)arg1;	// IMP=0x0000000100008180
- (void)wakeRequestedByClient:(id)arg1 forReason:(unsigned long long)arg2;	// IMP=0x0000000100007f68
- (void)sleepRequestedByClient:(id)arg1 forReason:(unsigned long long)arg2;	// IMP=0x0000000100007da8
- (void)client:(id)arg1 setSleepTimeout:(double)arg2;	// IMP=0x0000000100007c38
- (void)_stopBluetoothRemoteKeepAliveTimer;	// IMP=0x0000000100007be0
- (void)_startBluetoothRemoteKeepAliveTimer;	// IMP=0x0000000100007a6c
- (void)_keepBluetoothRemoteAlive;	// IMP=0x00000001000079d4
- (void)_handleDeviceWillSleepNotification:(id)arg1;	// IMP=0x0000000100007880
- (void)_handleDeviceWillWakeNotification:(id)arg1;	// IMP=0x00000001000077ec
- (void)_bluetoothRemotePowerSourceLimitedSourceNotification:(id)arg1;	// IMP=0x000000010000777c
- (void)_bluetoothRemoteDidConnectNotification:(id)arg1;	// IMP=0x0000000100007708
- (void)_blackScreenRecoveryModeNotification:(id)arg1;	// IMP=0x0000000100007654
- (void)_internetAvailabilityDidChangeNotification:(id)arg1;	// IMP=0x000000010000736c
- (void)_handleBluetoothRemoteProximityDetection;	// IMP=0x000000010000728c
- (void)client:(id)arg1 setIdleTimerDisabled:(_Bool)arg2;	// IMP=0x00000001000071d4
- (void)_handleFocusedProcessDidChange;	// IMP=0x00000001000070f0
- (void)_handleProcessDidExitNotification:(id)arg1;	// IMP=0x0000000100006fe0
- (void)_handUserDidIdle;	// IMP=0x0000000100006f94
- (void)_handleIdleBackgroundTasksTrigger:(id)arg1;	// IMP=0x0000000100006ef4
- (void)_handleBluetoothRemoteSleepTrigger:(id)arg1;	// IMP=0x0000000100006e94
- (void)_handleDevceSleepChange;	// IMP=0x0000000100006d80
- (void)_handleSleepTrigger:(id)arg1;	// IMP=0x0000000100006ccc
- (void)_handleScreenSaverTrigger:(id)arg1;	// IMP=0x0000000100006c38
- (void)_setHiliteModeActive:(_Bool)arg1;	// IMP=0x0000000100006a98
- (void)_handleHiliteModeTrigger:(id)arg1;	// IMP=0x0000000100006a60
- (void)_remotePresenceDetectionModeTrigger:(id)arg1;	// IMP=0x0000000100006a20
- (void)_handleIdleTimeoutDidChange;	// IMP=0x0000000100006a14
- (void)tvs_bindPowerManagerSleepBindingToObject:(id)arg1 withKeyPath:(id)arg2 options:(id)arg3;	// IMP=0x0000000100006920
- (id)PowerManagerSleepBinding;	// IMP=0x00000001000068ac
- (void)tvs_bindFocusedProcessBindingToObject:(id)arg1 withKeyPath:(id)arg2 options:(id)arg3;	// IMP=0x00000001000067b8
- (id)FocusedProcessBinding;	// IMP=0x0000000100006744
- (void)tvs_bindIdleTimeOutBindingToObject:(id)arg1 withKeyPath:(id)arg2 options:(id)arg3;	// IMP=0x0000000100006650
- (id)IdleTimeOutBinding;	// IMP=0x00000001000065dc
- (void)resetIdleTimerAndUndim;	// IMP=0x000000010000658c
- (void)_handleDisplayModeDidChange;	// IMP=0x00000001000064a8
- (void)_startDisplayManagement;	// IMP=0x0000000100006334
- (void)_adjustToDisplayChange;	// IMP=0x00000001000061c4
@property(readonly, nonatomic) _Bool isScreenSaverIdle;
- (void)resumeActivity;	// IMP=0x0000000100006124
- (void)stopAllActivity;	// IMP=0x00000001000060c0
- (_Bool)_validatePresses:(id)arg1 forWindow:(id)arg2;	// IMP=0x0000000100005f5c
- (void)_handleKeyUIEvent:(id)arg1;	// IMP=0x0000000100005e28
- (void)_sendButtonEventWithType:(long long)arg1 phase:(long long)arg2 timestamp:(double)arg3 synthetic:(_Bool)arg4;	// IMP=0x0000000100005dc4
- (_Bool)_prepareButtonEvent:(id)arg1 type:(long long)arg2 phase:(long long)arg3 timestamp:(double)arg4 force:(double)arg5 isSynthetic:(_Bool)arg6;	// IMP=0x0000000100005c04
- (_Bool)_handlePhysicalButtonEvent:(id)arg1;	// IMP=0x0000000100005a00
- (void)_processChordsWithPressesEvent:(id)arg1;	// IMP=0x0000000100005568
- (_Bool)_handleSystemPressHidEvent:(struct __IOHIDEvent *)arg1 withType:(long long)arg2;	// IMP=0x0000000100005414
- (id)keyCommands;	// IMP=0x0000000100005308
- (void)resignActive;	// IMP=0x0000000100005304
- (_Bool)_accessibilityIsSystemAppServer;	// IMP=0x00000001000052e0
- (void)dealloc;	// IMP=0x0000000100005264
- (void)finishSystemAppLaunch;	// IMP=0x0000000100004c18
- (id)init;	// IMP=0x0000000100004a0c

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

