//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PBApplication.h"

@interface PBApplication (PBApplicationTesting)
- (void)_startResumeTestNamed:(id)arg1 options:(id)arg2;	// IMP=0x000000010004d55c
- (void)_startLaunchTestNamed:(id)arg1 options:(id)arg2;	// IMP=0x000000010004d1ec
- (void)_retryLaunchTestWithOptions:(id)arg1;	// IMP=0x000000010004d114
- (void)_activateApplication:(id)arg1 suspended:(_Bool)arg2 forTest:(id)arg3;	// IMP=0x000000010004cf74
- (void)_markUserLaunchInitiationTimeForTest:(id)arg1;	// IMP=0x000000010004cea8
- (_Bool)_isAppExecutableRunning:(id)arg1;	// IMP=0x000000010004ce04
- (_Bool)runTest:(id)arg1 options:(id)arg2;	// IMP=0x000000010004ccbc
@end

