//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PBWindow.h"

@class PBWallpaperView;

@interface PBBackgroundWindow : PBWindow
{
    PBWallpaperView *_wallpaperView;	// 8 = 0x8
}

+ (id)sharedInstance;	// IMP=0x0000000100041718
@property(retain, nonatomic) PBWallpaperView *wallpaperView; // @synthesize wallpaperView=_wallpaperView;
- (void).cxx_destruct;	// IMP=0x0000000100041e54
- (void)exitIdleMode:(_Bool)arg1;	// IMP=0x0000000100041c24
- (void)enterIdleMode:(_Bool)arg1;	// IMP=0x0000000100041a3c
- (void)updateBackgroundWindowAndMakeVisible;	// IMP=0x00000001000419d0
- (id)initWithFrame:(struct CGRect)arg1;	// IMP=0x000000010004191c

@end

