//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDate, NSMutableDictionary, NSMutableSet;

@interface PBDataReportingService : NSObject
{
    NSMutableSet *_seenEDIDs;	// 8 = 0x8
    NSMutableDictionary *_toReportEDIDData;	// 16 = 0x10
    NSDate *_lastSentEDIDTimestamp;	// 24 = 0x18
}

+ (id)_sharedInstance;	// IMP=0x000000010002dacc
+ (id)diagnosticLogPaths;	// IMP=0x000000010002da70
+ (void)incrementScalarKey:(id)arg1;	// IMP=0x000000010002da00
+ (void)reportNow;	// IMP=0x000000010002d9b8
+ (void)startService;	// IMP=0x000000010002d940
@property(retain, nonatomic) NSDate *lastSentEDIDTimestamp; // @synthesize lastSentEDIDTimestamp=_lastSentEDIDTimestamp;
@property(retain, nonatomic) NSMutableDictionary *toReportEDIDData; // @synthesize toReportEDIDData=_toReportEDIDData;
@property(retain, nonatomic) NSMutableSet *seenEDIDs; // @synthesize seenEDIDs=_seenEDIDs;
- (void).cxx_destruct;	// IMP=0x000000010003441c
- (void)_reportBluetoothData;	// IMP=0x0000000100033ff0
- (void)_sendToURL:(id)arg1 withSubtopic:(id)arg2 andParameters:(id)arg3;	// IMP=0x0000000100033720
- (id)_reportingURLForTopic:(id)arg1;	// IMP=0x0000000100033364
- (void)_sendCoreControlUsage;	// IMP=0x00000001000332b0
- (void)_sendEDIDURLRequest:(id)arg1;	// IMP=0x000000010003309c
- (void)_sendEDIDLogs;	// IMP=0x0000000100032f28
- (void)_recordEDID;	// IMP=0x0000000100032bc8
- (void)_handleDisplayModeDidChange;	// IMP=0x0000000100032ad8
- (void)_showPushedIndicatorForCount:(unsigned long long)arg1;	// IMP=0x00000001000328b8
- (void)_pushDiagnosticLogsAtPaths:(id)arg1;	// IMP=0x0000000100032418
- (id)_collectConfigLogs;	// IMP=0x0000000100031e60
- (id)_collectBluetoothLogPaths;	// IMP=0x0000000100031b58
- (id)_collectThermalLogPaths;	// IMP=0x000000010003189c
- (id)_collectAirPlayLogPaths;	// IMP=0x0000000100030f68
- (id)_collectWiFiLogPaths;	// IMP=0x0000000100030134
- (id)_collectPlaybackLogPaths;	// IMP=0x000000010002fe3c
- (id)_collectMediaserverLogPaths;	// IMP=0x000000010002f2b8
- (id)_collectAVLog;	// IMP=0x000000010002ecd0
- (id)_collectLogPaths;	// IMP=0x000000010002ea04
- (void)_sendDiagnosticLogs:(id)arg1;	// IMP=0x000000010002e8a4
- (void)_reportDataNow;	// IMP=0x000000010002e434
- (void)_schedulePeriodicTrigger;	// IMP=0x000000010002e220
- (void)_configureEDIDReporting;	// IMP=0x000000010002e0fc
- (void)_configureThermalPressureReporting;	// IMP=0x000000010002df9c
- (void)_configureMemoryPressureReporting;	// IMP=0x000000010002df10
- (void)_configureAggregateDataReporting;	// IMP=0x000000010002dcec
- (_Bool)_isDiagnosticsSubmissionAllowed;	// IMP=0x000000010002dc48
- (id)init;	// IMP=0x000000010002db4c

@end

