//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "PBSBulletinServiceDelegate.h"

@class NSNumber, NSString, PBBulletinService, PBSBulletin;

@interface PBMediaRemoteObserver : NSObject <PBSBulletinServiceDelegate>
{
    PBBulletinService *_bulletinService;	// 8 = 0x8
    _Bool _metadataUpdateRunning;	// 16 = 0x10
    _Bool _playing;	// 17 = 0x11
    _Bool _playingMusic;	// 18 = 0x12
    _Bool _isMusicAppPlaying;	// 19 = 0x13
    int _nowPlayingProcessPID;	// 20 = 0x14
    NSNumber *_playbackRate;	// 24 = 0x18
    id <PBMediaRemoteObserverDelegate> _delegate;	// 32 = 0x20
    NSNumber *_trackIdentifier;	// 40 = 0x28
    NSString *_mediaType;	// 48 = 0x30
    PBSBulletin *_currentBulletin;	// 56 = 0x38
}

+ (id)_allAudioMediaTypes;	// IMP=0x000000010006efac
+ (id)_bulletinInfoForNowPlayingInfo:(id)arg1;	// IMP=0x000000010006ed3c
+ (id)sharedInstance;	// IMP=0x000000010006d534
@property(retain, nonatomic) PBSBulletin *currentBulletin; // @synthesize currentBulletin=_currentBulletin;
@property(readonly, copy, nonatomic) NSString *mediaType; // @synthesize mediaType=_mediaType;
@property(readonly, copy, nonatomic) NSNumber *trackIdentifier; // @synthesize trackIdentifier=_trackIdentifier;
@property(nonatomic) __weak id <PBMediaRemoteObserverDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;	// IMP=0x000000010006f114
- (void)_updateWithNowPlayingInfoDictionary:(id)arg1 playbackState:(unsigned int)arg2 nowPlayingPID:(int)arg3;	// IMP=0x000000010006e4cc
- (void)_performMetadataUpdate;	// IMP=0x000000010006de14
- (void)_setNeedsMetadataUpdate;	// IMP=0x000000010006dd70
- (void)_presentTrackChangeBulletinWithInfo:(id)arg1;	// IMP=0x000000010006db40
- (void)bulletinService:(id)arg1 didDismissBulletin:(id)arg2 withReason:(unsigned long long)arg3;	// IMP=0x000000010006db28
- (void)_nowPlayingAppDidChange:(id)arg1;	// IMP=0x000000010006db1c
- (void)_nowPlayingAppPlaybackStateDidChange:(id)arg1;	// IMP=0x000000010006d994
- (void)_nowPlayingInfoDidChange:(id)arg1;	// IMP=0x000000010006d988
@property(readonly, nonatomic) int nowPlayingProcessPID; // @synthesize nowPlayingProcessPID=_nowPlayingProcessPID;
@property(readonly, nonatomic) _Bool isMusicAppPlaying; // @synthesize isMusicAppPlaying=_isMusicAppPlaying;
@property(readonly, nonatomic) _Bool playingMusic; // @synthesize playingMusic=_playingMusic;
@property(readonly, nonatomic) _Bool playing; // @synthesize playing=_playing;
@property(readonly, copy, nonatomic) NSNumber *playbackRate; // @synthesize playbackRate=_playbackRate;
- (_Bool)nowPlayingMediaTypeAudioOnly;	// IMP=0x000000010006d784
- (void)stopObserving;	// IMP=0x000000010006d730
- (void)startObserving;	// IMP=0x000000010006d638
- (void)dealloc;	// IMP=0x000000010006d5e8

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

