//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSDictionary, NSSet;

@interface PBProgrammingGuide : NSObject
{
    int _reloadNotificationToken;	// 8 = 0x8
    id <PBCancellable> _programmingLoaderCancellation;	// 16 = 0x10
    id <PBCancellable> _mappingLoaderCancellation;	// 24 = 0x18
    _Bool _loadInProgressFlag;	// 32 = 0x20
    _Bool _needsReload;	// 33 = 0x21
    NSArray *_provisionedApplicationIdentifiers;	// 40 = 0x28
    NSSet *_disabledApplicationIdentifiers;	// 48 = 0x30
    NSDictionary *_applicationIdentifiersByBundleIdentifierMapping;	// 56 = 0x38
}

+ (id)sharedInstance;	// IMP=0x0000000100057e3c
@property(copy, nonatomic) NSDictionary *applicationIdentifiersByBundleIdentifierMapping; // @synthesize applicationIdentifiersByBundleIdentifierMapping=_applicationIdentifiersByBundleIdentifierMapping;
@property(copy, nonatomic) NSSet *disabledApplicationIdentifiers; // @synthesize disabledApplicationIdentifiers=_disabledApplicationIdentifiers;
@property(copy, nonatomic) NSArray *provisionedApplicationIdentifiers; // @synthesize provisionedApplicationIdentifiers=_provisionedApplicationIdentifiers;
- (void).cxx_destruct;	// IMP=0x0000000100059b5c
- (void)_addAutoInstallAdditionsToArray:(id)arg1;	// IMP=0x00000001000597a4
- (void)_updateProgrammingInfoWithCompletion:(CDUnknownBlockType)arg1;	// IMP=0x00000001000590fc
- (void)_updateMappingInfoWithCompletion:(CDUnknownBlockType)arg1;	// IMP=0x0000000100058cd4
- (void)_performUpdates;	// IMP=0x0000000100058858
- (void)_cancelPendingUpdates;	// IMP=0x00000001000587f0
- (void)_notifyProgrammingGuideDidUpdate;	// IMP=0x00000001000586a8
- (void)_reload;	// IMP=0x000000010005865c
- (void)_handleReloadTimer;	// IMP=0x0000000100058544
- (void)_handleForceReloadNotification;	// IMP=0x0000000100058414
- (void)setNeedsReload;	// IMP=0x0000000100058288
- (void)dealloc;	// IMP=0x00000001000580dc
- (id)_init;	// IMP=0x0000000100057ed4
- (id)init;	// IMP=0x0000000100057ebc

@end

