//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIWindow.h"

@interface PBSafeAreaWindow : UIWindow
{
}

- (void)drawRect:(struct CGRect)arg1;	// IMP=0x000000010001fd38
- (_Bool)_ignoresHitTest;	// IMP=0x000000010001fd30
- (_Bool)_canBecomeKeyWindow;	// IMP=0x000000010001fd28
- (id)initWithFrame:(struct CGRect)arg1;	// IMP=0x000000010001fc9c

@end

