//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "PBUIPluginHost.h"

@class NSString, UIViewController;

@interface PBSimplePluginHost : NSObject <PBUIPluginHost>
{
    UIViewController *_presentedViewController;	// 8 = 0x8
}

@property(retain, nonatomic) UIViewController *presentedViewController; // @synthesize presentedViewController=_presentedViewController;
- (void).cxx_destruct;	// IMP=0x000000010001f418
- (void)didChangeMode:(long long)arg1;	// IMP=0x000000010001f37c
- (void)dismissViewController:(id)arg1;	// IMP=0x000000010001f2c0
- (void)presentViewController:(id)arg1;	// IMP=0x000000010001f228
- (void)activateApplication:(id)arg1 openURL:(id)arg2 options:(id)arg3 completion:(CDUnknownBlockType)arg4;	// IMP=0x000000010001f0e8
- (void)activateApplication:(id)arg1 openURL:(id)arg2 completion:(CDUnknownBlockType)arg3;	// IMP=0x000000010001f078

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

