//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "AFContextProvider.h"

@interface PBSiriScreenActionContextProvider : NSObject <AFContextProvider>
{
}

+ (id)_JSONSerializedSemanticContext:(id)arg1;	// IMP=0x000000010004ca34
- (id)_screenActionInfoForScreenItem:(id)arg1;	// IMP=0x000000010004c74c
- (id)getCurrentContext;	// IMP=0x000000010004c16c
- (_Bool)allowContextProvider:(id)arg1;	// IMP=0x000000010004c164
- (void)dealloc;	// IMP=0x000000010004c0ac
- (id)init;	// IMP=0x000000010004bfec

@end

