//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class AXElement, NSArray, NSDictionary, NSString;

@interface PBSiriScreenActionApplication : NSObject
{
    NSDictionary *_semanticContext;	// 8 = 0x8
    AXElement *_accessibilityElement;	// 16 = 0x10
    NSArray *_commandScreenActionItems;	// 24 = 0x18
}

@property(copy, nonatomic) NSArray *commandScreenActionItems; // @synthesize commandScreenActionItems=_commandScreenActionItems;
@property(retain, nonatomic) AXElement *accessibilityElement; // @synthesize accessibilityElement=_accessibilityElement;
@property(retain, nonatomic) NSDictionary *semanticContext; // @synthesize semanticContext=_semanticContext;
- (void).cxx_destruct;	// IMP=0x000000010002cccc
- (id)_filteredScreenActionItems:(id)arg1 applicationScreenActionItems:(id)arg2 screenActionItemsWithSemanticContext:(id)arg3;	// IMP=0x000000010002c570
- (id)_screenActionItemsFromAccessibilityElements:(id)arg1;	// IMP=0x000000010002c3b4
- (id)_focusableScreenActionItems;	// IMP=0x000000010002c24c
- (id)_visibleScreenActionItemsWithSemanticContext;	// IMP=0x000000010002c0e4
- (id)screenActionItemForIdentifier:(id)arg1;	// IMP=0x000000010002bf44
@property(readonly, copy, nonatomic) NSArray *currentScreenActionItems;
@property(readonly, copy, nonatomic) NSString *bundleIdentifier;
- (id)initWithAccessibilityElement:(id)arg1;	// IMP=0x000000010002b5d8

@end

