//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class PBSiriScreenActionContextProvider, PBUIPluginController;

@interface PBSiriManager : NSObject
{
    _Bool _waitingForStartListening;	// 8 = 0x8
    _Bool _siriEnabled;	// 9 = 0x9
    PBUIPluginController *_siriPluginController;	// 16 = 0x10
    PBSiriScreenActionContextProvider *_onScreenActionContextProvider;	// 24 = 0x18
}

+ (_Bool)_isSiriEnabled;	// IMP=0x000000010008f070
+ (id)sharedInstance;	// IMP=0x000000010008e748
@property(retain, nonatomic) PBSiriScreenActionContextProvider *onScreenActionContextProvider; // @synthesize onScreenActionContextProvider=_onScreenActionContextProvider;
@property(retain, nonatomic) PBUIPluginController *siriPluginController; // @synthesize siriPluginController=_siriPluginController;
@property(nonatomic, getter=isSiriEnabled) _Bool siriEnabled; // @synthesize siriEnabled=_siriEnabled;
- (void).cxx_destruct;	// IMP=0x000000010008f83c
- (void)_stopProvidingScreenActionContext;	// IMP=0x000000010008f698
- (void)_startProvidingScreenActionContext;	// IMP=0x000000010008f3d4
- (id)_lazySiriPluginController;	// IMP=0x000000010008f258
- (void)_handleAssistantPreferencesDidChangeNotification:(id)arg1;	// IMP=0x000000010008f02c
- (_Bool)endSiriSession;	// IMP=0x000000010008ef64
- (void)setNextAssistantRecognitionStrings:(id)arg1;	// IMP=0x000000010008eef8
- (void)setNextVoiceRecognitionAudioInputPaths:(id)arg1;	// IMP=0x000000010008ee8c
- (_Bool)isListening;	// IMP=0x000000010008ed50
- (void)stopListening;	// IMP=0x000000010008ec20
- (void)startListening;	// IMP=0x000000010008eae0
- (void)activateUI;	// IMP=0x000000010008e9a0
- (_Bool)isWaitingForStartListening;	// IMP=0x000000010008e990
- (void)forgoWaitForStartListening;	// IMP=0x000000010008e980
- (void)waitForStartListening;	// IMP=0x000000010008e96c
- (void)prepareSiriViewServices;	// IMP=0x000000010008e92c
- (void)setup;	// IMP=0x000000010008e874
- (id)_init;	// IMP=0x000000010008e83c
- (id)init;	// IMP=0x000000010008e7fc

@end

