//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSDictionary, NSString, NSURL, NSXPCListenerEndpoint;

@protocol PBSystemServiceInterface <NSObject>
- (void)listen;
- (void)getAirPlayServiceProxyWithReply:(void (^)(id <PBSAirPlayServiceInterface>))arg1;
- (void)getOSUpdateServiceProxyWithReply:(void (^)(id <PBSOSUpdateServiceInterface>))arg1;
- (void)getDiagnosticLogsServiceProxyWithReply:(void (^)(id <PBSDiagnosticLogsServiceInterface>))arg1;
- (void)getBulletinServiceProxyWithReply:(void (^)(id <PBSBulletinServiceInterface>))arg1;
- (void)endpointForProviderType:(NSString *)arg1 withIdentifier:(NSString *)arg2 responseBlock:(void (^)(NSXPCListenerEndpoint *, NSError *))arg3;
- (void)registerServiceProviderEndpoint:(NSXPCListenerEndpoint *)arg1 forProviderType:(NSString *)arg2;
- (void)cancelScheduledAppActivation;
- (void)activateAppIfPlayingMusicAfterIdleTime:(double)arg1 openURL:(NSURL *)arg2;
- (void)performBluetoothRemoteFirmwareCheck;
- (void)pairAppleRemote:(_Bool)arg1 withReply:(void (^)(_Bool))arg2;
- (void)fetchPairedAppleRemoteStateWithReply:(void (^)(_Bool))arg1;
- (void)fetchProvisionAppIdentifiersWithReply:(void (^)(NSArray *))arg1;
- (void)fetchSharedAppStateWithReply:(void (^)(NSDictionary *))arg1;
- (void)sendMenuButtonEvent;
- (void)performScreenActionWithName:(NSString *)arg1 forItemIdentifier:(NSString *)arg2 parameters:(NSDictionary *)arg3 reply:(void (^)(_Bool, NSError *))arg4;
- (void)setNextAssistantRecognitionStrings:(NSArray *)arg1;
- (void)setNextVoiceRecognitionAudioInputPaths:(NSArray *)arg1;
- (void)topActiveOrActivatingApplicationIdentifierWithReply:(void (^)(NSString *, int))arg1;
- (void)recentApplicationBundleIdentifiersWithReply:(void (^)(NSArray *))arg1;
- (void)sleepTimeoutWithReply:(void (^)(double))arg1;
- (void)setSleepTimeout:(double)arg1;
- (void)purgeTopShelfContentForApplicationIdentifiers:(NSArray *)arg1;
- (void)setIgnoresAvailableDisplayModesChanges:(_Bool)arg1;
- (void)setAirPlayActive:(_Bool)arg1;
- (void)deactivateScreenSaver;
- (void)activateScreenSaver;
- (void)reboot;
- (void)relaunch;
- (void)relaunchBackboardd;
- (void)wakeSystemForReason:(unsigned long long)arg1;
- (void)sleepSystemForReason:(unsigned long long)arg1;
- (void)launchKioskApp;
- (void)deactivateApplication;
- (void)registerNowPlayingDelegate:(id <PBSystemServiceNowPlayingDelegate>)arg1;
@end

