//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSXPCListenerDelegate.h"

@class BKSProcessAssertion, NSMutableSet, NSObject<OS_dispatch_queue>, NSString, NSXPCListener, PBSystemServiceConnection;

@interface PBSystemService : NSObject <NSXPCListenerDelegate>
{
    NSObject<OS_dispatch_queue> *_acceptSerialQueue;	// 8 = 0x8
    NSXPCListener *_serviceListener;	// 16 = 0x10
    NSMutableSet *_activeConnections;	// 24 = 0x18
    BKSProcessAssertion *_processAssertion;	// 32 = 0x20
    PBSystemServiceConnection *_headBoardConnection;	// 40 = 0x28
    PBSystemServiceConnection *_idleScreenConnection;	// 48 = 0x30
}

+ (id)activeConnections;	// IMP=0x000000010004a964
+ (void)prepareForKioskAppTransitionWithCompletion:(CDUnknownBlockType)arg1;	// IMP=0x000000010004a8f8
+ (void)notifySharedAppStateDidChange;	// IMP=0x000000010004a8b8
+ (void)notifyStartIdleScreenAppTransitionForType:(long long)arg1 animationDuration:(double)arg2 animationFence:(id)arg3 currentTime:(double)arg4;	// IMP=0x000000010004a82c
+ (void)notifyStartKioskAppTransitionForType:(long long)arg1 animationDuration:(double)arg2 animationFence:(id)arg3 currentTime:(double)arg4;	// IMP=0x000000010004a7a0
+ (void)notifyKioskAppPurgeTopShelfContentForApplicationIdentifiers:(id)arg1;	// IMP=0x000000010004a734
+ (void)notifyKioskAppHandleHomeButtonWithCompletion:(CDUnknownBlockType)arg1;	// IMP=0x000000010004a6c8
+ (void)start;	// IMP=0x000000010004a614
+ (id)allocWithZone:(struct _NSZone *)arg1;	// IMP=0x000000010004a4f8
+ (id)_singleton;	// IMP=0x000000010004a444
@property(nonatomic) __weak PBSystemServiceConnection *idleScreenConnection; // @synthesize idleScreenConnection=_idleScreenConnection;
@property(nonatomic) __weak PBSystemServiceConnection *headBoardConnection; // @synthesize headBoardConnection=_headBoardConnection;
- (void).cxx_destruct;	// IMP=0x000000010004bb54
- (_Bool)listener:(id)arg1 shouldAcceptNewConnection:(id)arg2;	// IMP=0x000000010004b70c
- (void)_handleInvalidationForConnection:(id)arg1;	// IMP=0x000000010004b5cc
- (void)_startServices;	// IMP=0x000000010004b4f0
- (void)_prepareForKioskAppTransitionWithCompletion:(CDUnknownBlockType)arg1;	// IMP=0x000000010004b380
- (void)_notifySharedAppStateDidChange;	// IMP=0x000000010004b1e8
- (void)_notifyStartIdleScreenAppTransitionForType:(long long)arg1 animationDuration:(double)arg2 animationFence:(id)arg3 currentTime:(double)arg4;	// IMP=0x000000010004b078
- (void)_notifyStartKioskAppTransitionForType:(long long)arg1 animationDuration:(double)arg2 animationFence:(id)arg3 currentTime:(double)arg4;	// IMP=0x000000010004af08
- (void)_notifyKioskAppPurgeTopShelfContentForApplicationIdentifiers:(id)arg1;	// IMP=0x000000010004adc0
- (void)_notifyKioskAppHandleHomeButtonWithCompletion:(CDUnknownBlockType)arg1;	// IMP=0x000000010004aa00
- (id)_activeConnections;	// IMP=0x000000010004a9f0
- (id)init;	// IMP=0x000000010004a5fc
- (id)_init;	// IMP=0x000000010004a5c4

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

