//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface PBUnavailableBundleListLoader : NSObject
{
}

- (id)_numberArrayFromStringArray:(id)arg1;	// IMP=0x000000010004ee60
- (id)_documentLoaderWithRequest:(id)arg1;	// IMP=0x000000010004ed24
- (id)_computeRequestWithEndpoint:(id)arg1 error:(id *)arg2;	// IMP=0x000000010004eaf8
- (id)_santizeProgrammingInfo:(id)arg1 error:(id *)arg2;	// IMP=0x000000010004e8c4
- (id)_loadProgrammingInfoWithError:(id *)arg1;	// IMP=0x000000010004e48c
- (id)_santizeMappingInfo:(id)arg1 error:(id *)arg2;	// IMP=0x000000010004e1a8
- (id)_loadMappingInfoWithError:(id *)arg1;	// IMP=0x000000010004dd58
- (id)loadIdentifierMappingInfoWithCompletion:(CDUnknownBlockType)arg1;	// IMP=0x000000010004da48
- (id)loadProgrammingInfoWithCompletion:(CDUnknownBlockType)arg1;	// IMP=0x000000010004d738

@end

