//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "UNSystemStateProviding.h"

@class NSString;

@interface PBUserNotificationSystemStateProvider : NSObject <UNSystemStateProviding>
{
}

- (void)handleNewsstandNotificationForApplication:(id)arg1 userInfo:(id)arg2;	// IMP=0x000000010004d734
- (_Bool)shouldThrottleContentNotificationForApplicatin:(id)arg1 onDate:(id)arg2 withLastCount:(unsigned long long *)arg3 onDay:(long long *)arg4;	// IMP=0x000000010004d72c
- (_Bool)isNewsstandContentBackgroundModeSupportedForApplication:(id)arg1;	// IMP=0x000000010004d724
- (_Bool)isNewsstandApplication:(id)arg1;	// IMP=0x000000010004d71c
- (void)handleContentAvailableNotificationForApplication:(id)arg1 userInfo:(id)arg2 priority:(long long)arg3 completion:(CDUnknownBlockType)arg4;	// IMP=0x000000010004d670
- (_Bool)isRemoteNotificationBackgroundModeSupportedForApplication:(id)arg1;	// IMP=0x000000010004d668
- (_Bool)isBackgroundAppRefreshSupportedForApplication:(id)arg1;	// IMP=0x000000010004d660
- (_Bool)isApplicationRestricted:(id)arg1;	// IMP=0x000000010004d658
- (_Bool)isApplicationInstalled:(id)arg1;	// IMP=0x000000010004d5dc

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

