//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PBUserNotificationBaseViewController.h"

@interface PBUserNotificationViewControllerAlert : PBUserNotificationBaseViewController
{
}

- (void)_didSelectButtonAtIndex:(unsigned long long)arg1;	// IMP=0x0000000100091eec
- (void)updateWithNotification:(id)arg1;	// IMP=0x000000010009148c

@end

