//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TVSPeripheralManager.h"

@interface TVSPeripheralManager (B239)
+ (_Bool)_setInsomniaEnabledForRemote:(_Bool)arg1;	// IMP=0x000000010004bbfc
+ (_Bool)disableInsomnia;	// IMP=0x000000010004bbec
+ (_Bool)enableInsomnia;	// IMP=0x000000010004bbdc
@end

