//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class TVTermsAndConditionsView;

@protocol TVTermsAndConditionsViewDelegate <NSObject>
- (void)termsAndConditionsView:(TVTermsAndConditionsView *)arg1 didSelectButtonAtIndex:(long long)arg2;
@end

