#!/bin/bash

chown mobile:mobile /private/var/mobile
chown mobile:mobile /private/var/mobile/Library
chown -R mobile:mobile /private/var/mobile/Library/Preferences
chown root:wheel /fs/jb/Library/LaunchDaemons/com.nito.airmagicd.plist
launchctl unload /fs/jb/Library/LaunchDaemons/com.nito.airmagicd.plist
launchctl load /fs/jb/Library/LaunchDaemons/com.nito.airmagicd.plist
echo 'finish:restart'
