//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UICollectionView.h"

@interface _PBAppSwitcherCollectionView : UICollectionView
{
}

- (_Bool)_canScrollX;	// IMP=0x000000010003c744

@end

