//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@interface _PBAppSwitcherContentView : UIView
{
    UIView *_shadowImageView;	// 8 = 0x8
    UIView *_focusedShadowImageView;	// 16 = 0x10
    long long _state;	// 24 = 0x18
    UIView *_snapshotView;	// 32 = 0x20
    UIView *_backgroundView;	// 40 = 0x28
}

@property(readonly, nonatomic) UIView *backgroundView; // @synthesize backgroundView=_backgroundView;
@property(retain, nonatomic) UIView *snapshotView; // @synthesize snapshotView=_snapshotView;
@property(nonatomic) long long state; // @synthesize state=_state;
- (void).cxx_destruct;	// IMP=0x0000000100053668
- (struct CGAffineTransform)_transformForState:(long long)arg1;	// IMP=0x0000000100053548
- (double)_focusedShadowAlphaForState:(long long)arg1;	// IMP=0x0000000100053534
- (double)_shadowAlphaForState:(long long)arg1;	// IMP=0x000000010005351c
- (double)_backgroundAlphaForState:(long long)arg1;	// IMP=0x0000000100053508
- (void)_updateForStateChange;	// IMP=0x0000000100053258
- (id)initWithFrame:(struct CGRect)arg1;	// IMP=0x0000000100052ed0

@end

