//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UICollectionViewFlowLayout.h"

@class NSIndexPath;

@interface PBAppSwitcherFullscreenLayout : UICollectionViewFlowLayout
{
    NSIndexPath *_selectedIndexPath;	// 8 = 0x8
}

+ (struct CGSize)viewportSize;	// IMP=0x0000000100081554
@property(copy, nonatomic) NSIndexPath *selectedIndexPath; // @synthesize selectedIndexPath=_selectedIndexPath;
- (void).cxx_destruct;	// IMP=0x0000000100081a14
- (void)_adjustIconViewAttributes:(id)arg1;	// IMP=0x0000000100081998
- (id)finalLayoutAttributesForDisappearingSupplementaryElementOfKind:(id)arg1 atIndexPath:(id)arg2;	// IMP=0x0000000100081904
- (id)initialLayoutAttributesForAppearingSupplementaryElementOfKind:(id)arg1 atIndexPath:(id)arg2;	// IMP=0x0000000100081870
- (id)layoutAttributesForSupplementaryViewOfKind:(id)arg1 atIndexPath:(id)arg2;	// IMP=0x0000000100081808
- (struct CGPoint)targetContentOffsetForProposedContentOffset:(struct CGPoint)arg1;	// IMP=0x0000000100081744
- (id)init;	// IMP=0x00000001000815b8

@end

