//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UICollectionViewCell.h"

#import "UIGestureRecognizerDelegate.h"

@class NSString, UIPanGestureRecognizer, UITapGestureRecognizer, UIView, _PBAppSwitcherContentView, _UIFloatingContentView;

@interface PBAppSwitcherCollectionViewCell : UICollectionViewCell <UIGestureRecognizerDelegate>
{
    struct {
        unsigned int _respondsToCanRequestDelete:1;
    } _delegateFlags;	// 8 = 0x8
    _Bool _inDeleteGesture;	// 12 = 0xc
    _Bool _translationEnabled;	// 13 = 0xd
    struct CGPoint _initialDragLocation;	// 16 = 0x10
    UITapGestureRecognizer *_upRecognizer;	// 32 = 0x20
    UIPanGestureRecognizer *_panRecognizer;	// 40 = 0x28
    _PBAppSwitcherContentView *_draggingView;	// 48 = 0x30
    _PBAppSwitcherContentView *_snapshotContentView;	// 56 = 0x38
    _UIFloatingContentView *_floatingView;	// 64 = 0x40
    long long _cellState;	// 72 = 0x48
    id <PBAppSwitcherCollectionViewCellDelegate> _delegate;	// 80 = 0x50
}

@property(nonatomic) __weak id <PBAppSwitcherCollectionViewCellDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) long long cellState; // @synthesize cellState=_cellState;
- (void).cxx_destruct;	// IMP=0x000000010009b13c
- (void)_setTranslationEnabled:(_Bool)arg1;	// IMP=0x000000010009b0b0
- (void)_updateForCellStateChange;	// IMP=0x000000010009b020
- (void)panGestureRecognizerMoved:(id)arg1;	// IMP=0x000000010009a9d0
- (void)upDoubleTapped:(id)arg1;	// IMP=0x000000010009a7f0
- (_Bool)gestureRecognizerShouldBegin:(id)arg1;	// IMP=0x000000010009a744
@property(retain, nonatomic) UIView *snapshotView;
- (void)layoutSubviews;	// IMP=0x000000010009a484
- (void)prepareForReuse;	// IMP=0x000000010009a380
- (id)initWithFrame:(struct CGRect)arg1;	// IMP=0x000000010009a01c

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

