//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "PBAppTransitionContextDelegate.h"

@class NSString, PBAppTransitionContext, PBAppTransitionTransaction, TVSStateMachine, UIView;

@interface PBAppTransitionViewController : UIViewController <PBAppTransitionContextDelegate>
{
    _Bool _launchedProcess;	// 8 = 0x8
    _Bool _shouldUseLaunchImage;	// 9 = 0x9
    _Bool _processIsForeground;	// 10 = 0xa
    PBAppTransitionTransaction *_transitionTransaction;	// 16 = 0x10
    CDUnknownBlockType _completion;	// 24 = 0x18
    PBAppTransitionContext *_context;	// 32 = 0x20
    UIView *_fromView;	// 40 = 0x28
    UIView *_toView;	// 48 = 0x30
    long long _transitionType;	// 56 = 0x38
    TVSStateMachine *_stateMachine;	// 64 = 0x40
    UIView *_intermediateView;	// 72 = 0x48
    NSString *_kioskIdentifier;	// 80 = 0x50
}

+ (double)animationDurationForTransitionType:(long long)arg1;	// IMP=0x000000010005b728
+ (id)launchViewForBundleIdentifier:(id)arg1;	// IMP=0x000000010005afc0
@property(copy, nonatomic) NSString *kioskIdentifier; // @synthesize kioskIdentifier=_kioskIdentifier;
@property(retain, nonatomic) UIView *intermediateView; // @synthesize intermediateView=_intermediateView;
@property(retain, nonatomic) TVSStateMachine *stateMachine; // @synthesize stateMachine=_stateMachine;
@property(readonly, nonatomic) long long transitionType; // @synthesize transitionType=_transitionType;
@property(readonly, nonatomic) _Bool processIsForeground; // @synthesize processIsForeground=_processIsForeground;
@property(readonly, nonatomic) _Bool shouldUseLaunchImage; // @synthesize shouldUseLaunchImage=_shouldUseLaunchImage;
@property(readonly, nonatomic) _Bool launchedProcess; // @synthesize launchedProcess=_launchedProcess;
@property(retain, nonatomic) UIView *toView; // @synthesize toView=_toView;
@property(retain, nonatomic) UIView *fromView; // @synthesize fromView=_fromView;
@property(retain, nonatomic) PBAppTransitionContext *context; // @synthesize context=_context;
@property(copy, nonatomic) CDUnknownBlockType completion; // @synthesize completion=_completion;
@property(retain, nonatomic) PBAppTransitionTransaction *transitionTransaction; // @synthesize transitionTransaction=_transitionTransaction;
- (void).cxx_destruct;	// IMP=0x0000000100060704
- (void)_configureStateMachineForAppSwitcherToLiveApp;	// IMP=0x000000010005fe8c
- (void)_foregroundUpdateForRunningApp;	// IMP=0x000000010005fe4c
- (void)_beginSwitchAnimationForLiveApp;	// IMP=0x000000010005fb3c
- (void)_configureStateMachineForAppSwitcherToSuspendedApp;	// IMP=0x000000010005f1ec
- (void)_finalSwitchAnimationForSuspendedApp;	// IMP=0x000000010005ef50
- (void)_beginSwitchAnimationForSuspendedApp;	// IMP=0x000000010005e8ac
- (void)_configureStateMachineForLaunchingRunningApp;	// IMP=0x000000010005e180
- (void)_finalLaunchingAnimationForRunningApp;	// IMP=0x000000010005dcc0
- (void)_beginLaunchingAnimationForRunningApp;	// IMP=0x000000010005d67c
- (void)_configureStateMachineForLaunchingNewApp;	// IMP=0x000000010005cd2c
- (void)_finalLaunchingAnimationForNewApp;	// IMP=0x000000010005ca10
- (void)_beginLaunchingAnimationForNewApp;	// IMP=0x000000010005c394
- (void)_complete;	// IMP=0x000000010005c054
- (void)contextTransitionDidFail:(id)arg1;	// IMP=0x000000010005c00c
- (void)contextReadyForFinalTransition:(id)arg1;	// IMP=0x000000010005bfc4
- (void)contextForegroundUpdateComplete:(id)arg1;	// IMP=0x000000010005bf7c
- (void)_applyAnimationsForView:(id)arg1 duration:(double)arg2 delay:(double)arg3;	// IMP=0x000000010005b74c
@property(readonly, nonatomic) double animationDuration;
- (_Bool)isAnimatingOutward;	// IMP=0x000000010005b698
- (void)viewDidLoad;	// IMP=0x000000010005a9f8
- (void)abortTransition;	// IMP=0x000000010005a9b8
- (_Bool)isSwitchingFromSetup;	// IMP=0x000000010005a994
- (_Bool)isSwitchingToKiosk;	// IMP=0x000000010005a930
- (_Bool)isSwitchingToIdle;	// IMP=0x000000010005a8e0
- (_Bool)isSwitchingFromKiosk;	// IMP=0x000000010005a890
- (_Bool)isSwitchingFromIdle;	// IMP=0x000000010005a840
- (id)initWithTransitionTransaction:(id)arg1;	// IMP=0x000000010005a1f0
- (id)initWithCoder:(id)arg1;	// IMP=0x000000010005a1a4
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;	// IMP=0x000000010005a148

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

