//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIResponder.h"

#import "FBApplicationTerminationAssertionServiceDelegate.h"
#import "LSApplicationWorkspaceObserverProtocol.h"
#import "PBLanguageChangeObserverDelegate.h"
#import "PBMediaRemoteObserverDelegate.h"
#import "UIApplicationDelegate.h"

@class BBDataProviderConnection, NSMutableOrderedSet, NSObject<OS_dispatch_queue>, NSString, PBLanguageChangeObserver, PBSafeAreaWindow, PBSerialNumberWindow, PBUserNotificationHandler, TVSAudioRoutingController, TVSBackgroundTask, TVSUserActivityTrigger, UIWindow;

@interface PBAppDelegate : UIResponder <FBApplicationTerminationAssertionServiceDelegate, LSApplicationWorkspaceObserverProtocol, PBMediaRemoteObserverDelegate, PBLanguageChangeObserverDelegate, UIApplicationDelegate>
{
    PBUserNotificationHandler *_userNotificationHandler;	// 8 = 0x8
    PBSafeAreaWindow *_safeAreaWindow;	// 16 = 0x10
    PBSerialNumberWindow *_serialNumberWindow;	// 24 = 0x18
    TVSUserActivityTrigger *_musicNowPlayingTrigger;	// 32 = 0x20
    _Bool _isRadioAdPlaying;	// 40 = 0x28
    _Bool _isShowingRadioAdView;	// 41 = 0x29
    _Bool _inhibitAppLaunch;	// 42 = 0x2a
    _Bool _tooHot;	// 43 = 0x2b
    _Bool _awaitingAppDeactivation;	// 44 = 0x2c
    _Bool _awaitingFirstAppLaunch;	// 45 = 0x2d
    BBDataProviderConnection *_bulletinBoardConnection;	// 48 = 0x30
    NSObject<OS_dispatch_queue> *_bulletinBoardQueue;	// 56 = 0x38
    _Bool _shouldDisableIdleTimer;	// 64 = 0x40
    TVSBackgroundTask *_programmingGuideBackgroundTask;	// 72 = 0x48
    id _buddyPrefsObservingToken;	// 80 = 0x50
    NSMutableOrderedSet *_mutableDeepLinkingAppHistory;	// 88 = 0x58
    PBLanguageChangeObserver *_languageChangeObserver;	// 96 = 0x60
    TVSAudioRoutingController *_audioRoutingController;	// 104 = 0x68
}

+ (id)sharedApplicationDelegate;	// IMP=0x0000000100076398
@property(retain, nonatomic) TVSAudioRoutingController *audioRoutingController; // @synthesize audioRoutingController=_audioRoutingController;
@property(nonatomic) _Bool shouldDisableIdleTimer; // @synthesize shouldDisableIdleTimer=_shouldDisableIdleTimer;
@property(retain, nonatomic) PBLanguageChangeObserver *languageChangeObserver; // @synthesize languageChangeObserver=_languageChangeObserver;
@property(readonly, nonatomic) NSMutableOrderedSet *mutableDeepLinkingAppHistory; // @synthesize mutableDeepLinkingAppHistory=_mutableDeepLinkingAppHistory;
@property(retain, nonatomic) id buddyPrefsObservingToken; // @synthesize buddyPrefsObservingToken=_buddyPrefsObservingToken;
@property(retain, nonatomic) TVSBackgroundTask *programmingGuideBackgroundTask; // @synthesize programmingGuideBackgroundTask=_programmingGuideBackgroundTask;
- (void).cxx_destruct;	// IMP=0x0000000100080788
- (void)applicationsDidUninstall:(id)arg1;	// IMP=0x000000010008045c
- (void)applicationsDidInstall:(id)arg1;	// IMP=0x00000001000803ec
- (void)_assertApplicationForBundleIdentifier:(id)arg1 allowsCacheDeletionWithError:(id *)arg2;	// IMP=0x0000000100080248
- (void)_assertApplicationForBundleIdentifier:(id)arg1 notInUseWithError:(id *)arg2;	// IMP=0x00000001000800cc
- (void)service:(id)arg1 didRelinquishTerminationAssertion:(id)arg2;	// IMP=0x000000010007fffc
- (void)service:(id)arg1 didAcquireTerminationAssertion:(id)arg2;	// IMP=0x000000010007fe28
- (void)service:(id)arg1 canAcquireTerminationAssertion:(id)arg2 completionHandler:(CDUnknownBlockType)arg3;	// IMP=0x000000010007fc98
- (void)_setLateNightModeEnabled:(_Bool)arg1;	// IMP=0x000000010007fbe4
- (void)_handleDisableLateNightModeNotification:(id)arg1;	// IMP=0x000000010007fbd4
- (void)_handleEnableLateNightModeNotification:(id)arg1;	// IMP=0x000000010007fbc4
- (void)_performObliterationIfNeeded;	// IMP=0x000000010007f45c
- (void)_dequeuePendingProfiles;	// IMP=0x000000010007f1f0
- (void)_prepareForDeviceWake;	// IMP=0x000000010007f130
- (void)_prepareForDeviceSleep;	// IMP=0x000000010007f120
- (void)_setConstantAudioOutputEnabled:(_Bool)arg1;	// IMP=0x000000010007f0bc
- (void)_updateConstantAudioOutput;	// IMP=0x000000010007efec
- (void)_dismissRadioAdViewController;	// IMP=0x000000010007efa4
- (void)_showRadioAdViewController;	// IMP=0x000000010007eee8
- (void)_presentNowPlayingViewController:(id)arg1;	// IMP=0x000000010007ee30
- (_Bool)_presentNowPlayingSystemUIWithOptions:(id)arg1;	// IMP=0x000000010007ec44
- (_Bool)_sendFocusedAppMessagePresentNowPlayingUI;	// IMP=0x000000010007ebb4
- (void)_displayDialogForPermissionRequest:(id)arg1 fromResponder:(id)arg2;	// IMP=0x000000010007e5d0
- (_Bool)handlePermissionRequest:(id)arg1;	// IMP=0x000000010007e36c
- (_Bool)_nowPlayingAppFocused;	// IMP=0x000000010007e24c
- (_Bool)_shouldShowSiri;	// IMP=0x000000010007e1c4
- (void)_setupWebinspector;	// IMP=0x000000010007e15c
- (void)_startObservingPurpleBuddyPrefs;	// IMP=0x000000010007e098
- (_Bool)_shouldEnableNavigationSoundsForBundleIdentifier:(id)arg1;	// IMP=0x000000010007e00c
- (void)_resumeActivity;	// IMP=0x000000010007dec4
- (void)_stopAllActivity;	// IMP=0x000000010007dc14
- (void)_pausePlayback;	// IMP=0x000000010007dc04
- (void)_handleThermalNotification:(id)arg1;	// IMP=0x000000010007d89c
- (void)_getNowPlayingViewControllerClassName:(id *)arg1 serviceIdentifier:(id *)arg2;	// IMP=0x000000010007d3a0
- (void)_handleMusicNowPlayingTrigger:(id)arg1;	// IMP=0x000000010007d1c4
- (void)_setIdleTimerDisabled:(_Bool)arg1;	// IMP=0x000000010007d1ac
- (void)_loadBundles;	// IMP=0x000000010007d164
- (void)_configureAskPermission;	// IMP=0x000000010007d048
- (void)_launchTVSettingsWithOpenURL:(id)arg1;	// IMP=0x000000010007cee8
- (void)_launchTVSettings;	// IMP=0x000000010007ced8
- (void)_launchTVApp;	// IMP=0x000000010007cca4
- (_Bool)_launchNowPlayingApp;	// IMP=0x000000010007cb94
- (void)_launchPurpleBuddy;	// IMP=0x000000010007c9c8
- (void)_launchTVAirPlay;	// IMP=0x000000010007c870
- (void)_ensureTVAirPlayRunning;	// IMP=0x000000010007c7cc
- (void)deactivateFocusedApp;	// IMP=0x000000010007c6bc
- (void)launchKioskAppFromSetup;	// IMP=0x000000010007c270
- (void)launchKioskApp;	// IMP=0x000000010007c1a4
- (id)_kioskAppBundleID;	// IMP=0x000000010007c12c
- (void)_updateNowPlayingTrigger;	// IMP=0x000000010007c028
- (void)_sendActionOrShowUnconfiguredAlertForAction:(long long)arg1;	// IMP=0x000000010007bbe8
- (void)_startBulletinBoardServer;	// IMP=0x000000010007bad0
- (void)_handleStoreAccountChangedNotification;	// IMP=0x000000010007b9f4
- (void)_resetProgrammingGuideRefreshTaskWithTimeIntervalInSeconds:(double)arg1;	// IMP=0x000000010007b8c4
- (void)_updateProgrammingGuide;	// IMP=0x000000010007b71c
- (void)_performInitialSoftwareUpdateCheckIfNecessary;	// IMP=0x000000010007b5dc
- (void)_updateSoftwareUpdateServiceURLBagConfiguration;	// IMP=0x000000010007b458
- (void)_startStoreURLBagMonitoring;	// IMP=0x000000010007b210
- (void)_handleProgrammingGuideDidUpdateNotification;	// IMP=0x000000010007b194
- (void)_handleStoreURLBagDidLoadNotification;	// IMP=0x000000010007b150
- (void)_kickoffAppDepotReload;	// IMP=0x000000010007b0b8
- (void)appTransitionDidCompleteForInitiator:(id)arg1;	// IMP=0x000000010007aef4
- (void)observer:(id)arg1 didObserveLanguageChange:(_Bool)arg2 localeChange:(_Bool)arg3;	// IMP=0x000000010007acd0
- (void)_setupLanguageChangeObserving;	// IMP=0x000000010007ac08
- (void)mediaRemoteObserverNowPlayingInfoDidChange:(id)arg1 nowPlayingInfo:(id)arg2;	// IMP=0x000000010007aab8
- (void)mediaRemoteObserverNowPlayingAppDidChange:(id)arg1;	// IMP=0x000000010007aa0c
- (void)mediaRemoteObserverIsPlayingDidChange:(id)arg1;	// IMP=0x000000010007a86c
- (_Bool)mediaRemoteObserverShouldShowTrackChangeBulletin:(id)arg1;	// IMP=0x000000010007a708
- (_Bool)_wouldExpectPlayPauseLongPressShouldPresentNowPlayingSystemUI;	// IMP=0x000000010007a564
- (_Bool)_wouldExpectPlayPauseButtonDownShouldPause;	// IMP=0x000000010007a480
- (void)handleDirectionalTapEvent:(id)arg1;	// IMP=0x000000010007a39c
- (void)handleSelectTapEvent;	// IMP=0x000000010007a300
- (void)handleTVLongPressEvent:(id)arg1;	// IMP=0x000000010007a1fc
- (void)handleTVTripleTapEvent;	// IMP=0x000000010007a1b0
- (void)handleTVDoubleTapEvent;	// IMP=0x0000000100079fc0
- (void)handleTVTapEvent;	// IMP=0x0000000100079d34
- (void)handleVolumeDownLongPressEvent:(id)arg1;	// IMP=0x0000000100079c50
- (void)handleVolumeUpLongPressEvent:(id)arg1;	// IMP=0x0000000100079b6c
- (void)handlePlayPauseLongPressEvent:(id)arg1;	// IMP=0x0000000100079a6c
- (void)handleFastForwardLongPressEvent:(id)arg1;	// IMP=0x0000000100079a00
- (void)handleRewindLongPressEvent:(id)arg1;	// IMP=0x0000000100079994
- (void)handleSkipBackwardsRepeatingPressEvent:(id)arg1;	// IMP=0x0000000100079978
- (void)handleSkipForwardsRepeatingPressEvent:(id)arg1;	// IMP=0x000000010007995c
- (void)_handleSkipGestureRecognizer:(id)arg1 withCommand:(unsigned int)arg2 interval:(double)arg3;	// IMP=0x000000010007986c
- (void)handlePreviousTrackTapEvent;	// IMP=0x000000010007985c
- (void)handleNextTrackTapEvent;	// IMP=0x000000010007984c
- (void)handleFastForwardTapEvent;	// IMP=0x0000000100079820
- (void)handleRewindTapEvent;	// IMP=0x00000001000797f4
- (void)_changePlaybackRateWithBlock:(CDUnknownBlockType)arg1;	// IMP=0x000000010007968c
- (void)handleStopTapEvent;	// IMP=0x000000010007967c
- (void)handlePauseTapEvent;	// IMP=0x000000010007966c
- (void)handlePlayTapEvent;	// IMP=0x000000010007965c
- (void)handlePlayPauseTapEvent;	// IMP=0x00000001000795b4
- (_Bool)shouldTogglePlayPauseOnButtonDown;	// IMP=0x0000000100079540
- (void)_sendMediaRemoteCommand:(unsigned int)arg1;	// IMP=0x0000000100079530
- (void)_sendMediaRemoteCommand:(unsigned int)arg1 withOptions:(id)arg2;	// IMP=0x000000010007949c
- (_Bool)_shouldSendMediaRemoteCommand:(unsigned int)arg1;	// IMP=0x00000001000792a8
- (void)handleMicrophoneButtonDownEvent;	// IMP=0x0000000100079244
- (void)handleMicrophoneLongPressEvent:(id)arg1;	// IMP=0x0000000100079180
- (void)handleMicrophoneTapEvent;	// IMP=0x00000001000790c0
- (_Bool)handleUnhandledMenuEvent;	// IMP=0x0000000100078f84
- (void)_updateTripleTapMenu;	// IMP=0x0000000100078e98
- (void)handleMenuLongPressEvent:(id)arg1;	// IMP=0x0000000100078c28
- (void)handleMenuSingleTapEvent;	// IMP=0x0000000100078acc
- (void)handleMenuDoubleTapEvent;	// IMP=0x0000000100078ac8
- (void)handleMenuTripleTapEvent;	// IMP=0x0000000100078988
- (void)_registerProcessManagerNotificationHandlers;	// IMP=0x0000000100078214
- (void)_startSteadyStateServices;	// IMP=0x000000010007814c
- (void)_handleProcessDidActivate:(id)arg1 suspended:(_Bool)arg2;	// IMP=0x0000000100077dc0
- (void)_handleProcessWillActivate:(id)arg1 suspended:(_Bool)arg2;	// IMP=0x0000000100077d10
- (void)_handleProcessDidExit:(id)arg1;	// IMP=0x0000000100077b00
- (void)_handlePineBoardPrefsDidChange;	// IMP=0x0000000100077aac
- (_Bool)application:(id)arg1 openURL:(id)arg2 options:(id)arg3;	// IMP=0x00000001000779b4
- (_Bool)application:(id)arg1 didFinishLaunchingWithOptions:(id)arg2;	// IMP=0x0000000100076828
- (void)tvs_bindAccessibilityMenuOptionsBindingToObject:(id)arg1 withKeyPath:(id)arg2 options:(id)arg3;	// IMP=0x0000000100076734
- (id)AccessibilityMenuOptionsBinding;	// IMP=0x00000001000766c0
@property(readonly, nonatomic) TVSUserActivityTrigger *musicNowPlayingTrigger;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;	// IMP=0x0000000100076524
- (void)dealloc;	// IMP=0x000000010007647c
- (id)init;	// IMP=0x00000001000763f4

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;
@property(retain, nonatomic) UIWindow *window;

@end

