//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "PBAppSwitcherCollectionViewControllerDelegate.h"

@class NSString, PBAppSwitcherCollectionViewController, PBAppTransitionContext;

@interface PBAppSwitcherViewController : UIViewController <PBAppSwitcherCollectionViewControllerDelegate>
{
    PBAppTransitionContext *_activeTransitionContext;	// 8 = 0x8
    PBAppSwitcherCollectionViewController *_collectionViewController;	// 16 = 0x10
    CDUnknownBlockType _transitionCompletion;	// 24 = 0x18
}

@property(copy, nonatomic) CDUnknownBlockType transitionCompletion; // @synthesize transitionCompletion=_transitionCompletion;
@property(retain, nonatomic) PBAppSwitcherCollectionViewController *collectionViewController; // @synthesize collectionViewController=_collectionViewController;
@property(retain, nonatomic) PBAppTransitionContext *activeTransitionContext; // @synthesize activeTransitionContext=_activeTransitionContext;
- (void).cxx_destruct;	// IMP=0x0000000100081500
- (void)_handleCompletionWithSuccess:(_Bool)arg1;	// IMP=0x00000001000813a8
- (void)viewController:(id)arg1 readyForExitToAppWithIdentifer:(id)arg2;	// IMP=0x0000000100081398
- (id)preferredFocusedItem;	// IMP=0x0000000100081388
- (void)exitToCurrentApplication;	// IMP=0x0000000100081370
- (void)handleTransitionWithContext:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x0000000100081240
- (void)loadView;	// IMP=0x0000000100081018

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

