//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "TVSCoreControlManagerDelegate.h"

@class NSString, TVSAudioRoutingController, TVSCoreControlManager;

@interface PBCoreControlManager : NSObject <TVSCoreControlManagerDelegate>
{
    TVSCoreControlManager *_coreControlMgr;	// 8 = 0x8
    id <NSObject> _notificationToken;	// 16 = 0x10
    TVSAudioRoutingController *_audioRoutingController;	// 24 = 0x18
}

+ (_Bool)volumeControlNeedsConfiguring;	// IMP=0x000000010008d4d4
+ (id)sharedManager;	// IMP=0x000000010008d478
@property(retain, nonatomic) TVSAudioRoutingController *audioRoutingController; // @synthesize audioRoutingController=_audioRoutingController;
@property(retain, nonatomic) id <NSObject> notificationToken; // @synthesize notificationToken=_notificationToken;
@property(retain, nonatomic) TVSCoreControlManager *coreControlMgr; // @synthesize coreControlMgr=_coreControlMgr;
- (void).cxx_destruct;	// IMP=0x000000010008e518
- (void)coreControlManagerDidRequestAlternateRouteVolumeDecrease:(id)arg1;	// IMP=0x000000010008e418
- (void)coreControlManagerDidRequestAlternateRouteVolumeIncrease:(id)arg1;	// IMP=0x000000010008e3cc
- (void)coreControlManagerDidUpdatePolicy:(id)arg1;	// IMP=0x000000010008ddd4
- (void)coreControlManager:(id)arg1 didReceiveRequest:(long long)arg2;	// IMP=0x000000010008d9b4
- (void)dealloc;	// IMP=0x000000010008d920
- (id)init;	// IMP=0x000000010008d6b8

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

