//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PBCoreControlManager.h"

@interface PBCoreControlManager (Private)
+ (id)_sharedInstance;	// IMP=0x000000010008e56c
- (void)_handleDisplayModeDidChange;	// IMP=0x000000010008e5ec
@end

