//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TVSCVVVerificationOperation.h"

#import "PBTextEntryViewControllerDelegate.h"

@class NSString;

@interface PBCVVVerificationOperation : TVSCVVVerificationOperation <PBTextEntryViewControllerDelegate>
{
    CDUnknownBlockType _completion;	// 120 = 0x78
}

@property(copy, nonatomic) CDUnknownBlockType completion; // @synthesize completion=_completion;
- (void).cxx_destruct;	// IMP=0x000000010001fc88
- (void)textEntryDidCancel:(id)arg1;	// IMP=0x000000010001fbac
- (void)textEntry:(id)arg1 didSelectButtonAtIndex:(unsigned long long)arg2;	// IMP=0x000000010001faa0
- (void)presentFailureAlertWithTitle:(id)arg1 message:(id)arg2 completion:(CDUnknownBlockType)arg3;	// IMP=0x000000010001f6f8
- (void)presentAlertWithTitle:(id)arg1 message:(id)arg2 completion:(CDUnknownBlockType)arg3;	// IMP=0x000000010001f42c

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

