//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PBWindow.h"

@interface PBHUDWindow : PBWindow
{
}

- (_Bool)_ignoresHitTest;	// IMP=0x000000010008e740
- (_Bool)_canBecomeKeyWindow;	// IMP=0x000000010008e738

@end

