//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TVNavigationController.h"

@interface PBNavigationController : TVNavigationController
{
    CDUnknownBlockType _dismissLastViewControllerBlock;	// 8 = 0x8
}

@property(copy, nonatomic) CDUnknownBlockType dismissLastViewControllerBlock; // @synthesize dismissLastViewControllerBlock=_dismissLastViewControllerBlock;
- (void).cxx_destruct;	// IMP=0x00000001000422a0
- (id)_lastViewController;	// IMP=0x00000001000421fc
- (void)_innerDismissViewControllerWithCompletion:(CDUnknownBlockType)arg1;	// IMP=0x000000010004216c
- (void)removeViewController:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x0000000100041fd8
- (void)dismissViewControllerAnimated:(_Bool)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x0000000100041e68

@end

