//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "PBSOSUpdateServiceInterface.h"

@class NSString, PBSystemServiceConnection;

@interface PBOSUpdateService : NSObject <PBSOSUpdateServiceInterface>
{
    id <PBSOSUpdateServiceDelegate> _delegate;	// 8 = 0x8
    PBSystemServiceConnection *_remoteConnection;	// 16 = 0x10
}

+ (void)_obliterateDataPreservingPaths:(id)arg1 withCompletion:(CDUnknownBlockType)arg2;	// IMP=0x00000001000444d4
@property(readonly, nonatomic) PBSystemServiceConnection *remoteConnection; // @synthesize remoteConnection=_remoteConnection;
- (void).cxx_destruct;	// IMP=0x0000000100044e18
- (void)didFinishApplyWithData:(id)arg1;	// IMP=0x0000000100044de8
- (void)didEncounterSlowUpdateWithData:(id)arg1;	// IMP=0x0000000100044dc8
- (void)didUpdateApplyProgressWithData:(id)arg1;	// IMP=0x0000000100044da8
- (void)didStartApplyWithData:(id)arg1;	// IMP=0x0000000100044d88
- (void)didStartRedownloadWithData:(id)arg1;	// IMP=0x0000000100044d68
- (void)didFinishDownloadWithData:(id)arg1;	// IMP=0x0000000100044d48
- (void)didUpdateDownloadProgressWithData:(id)arg1;	// IMP=0x0000000100044d28
- (void)didStartDownloadWithData:(id)arg1;	// IMP=0x0000000100044d08
- (void)didFinishCheckWithData:(id)arg1;	// IMP=0x0000000100044ce8
- (void)didStartCheckWithData:(id)arg1;	// IMP=0x0000000100044cc8
- (void)obliterateDataPreservingPaths:(id)arg1 withCompletion:(CDUnknownBlockType)arg2;	// IMP=0x0000000100044c54
- (void)cancelUpdate;	// IMP=0x0000000100044bec
- (void)isUpdateRunningWithCompletion:(CDUnknownBlockType)arg1;	// IMP=0x0000000100044ad8
- (void)restore;	// IMP=0x0000000100044a84
- (void)checkForUpdate;	// IMP=0x0000000100044a30
- (void)setDelegate:(id)arg1;	// IMP=0x0000000100044a1c
- (void)invalidate;	// IMP=0x0000000100044a18
- (id)initWithRemoteConnection:(id)arg1;	// IMP=0x000000010004498c
- (id)init;	// IMP=0x0000000100044974

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

