//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "_UIRemoteViewController.h"

@interface PBRemoteBulletinViewController : _UIRemoteViewController
{
    CDUnknownBlockType _clientPresentationCompletion;	// 8 = 0x8
}

+ (id)serviceViewControllerInterface;	// IMP=0x0000000100048620
@property(copy, nonatomic) CDUnknownBlockType clientPresentationCompletion; // @synthesize clientPresentationCompletion=_clientPresentationCompletion;
- (void).cxx_destruct;	// IMP=0x0000000100048f64
- (void)_callClientCompletionWithSuccess:(_Bool)arg1 error:(id)arg2;	// IMP=0x0000000100048e8c
- (void)viewServiceDidTerminateWithError:(id)arg1;	// IMP=0x0000000100048e30
- (void)viewDidAppear:(_Bool)arg1;	// IMP=0x0000000100048dd4
- (void)dismissViewServiceWithReason:(unsigned long long)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x00000001000487dc
- (void)updateViewServiceWithBulletin:(id)arg1;	// IMP=0x0000000100048770
- (void)prepareViewServiceWithBulletin:(id)arg1;	// IMP=0x0000000100048704

@end

