//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class AXElement, NSDictionary, NSString;

@interface PBSiriScreenActionItem : NSObject
{
    NSString *_identifier;	// 8 = 0x8
    NSDictionary *_semanticContext;	// 16 = 0x10
    AXElement *_accessibilityElement;	// 24 = 0x18
}

@property(retain, nonatomic) AXElement *accessibilityElement; // @synthesize accessibilityElement=_accessibilityElement;
@property(retain, nonatomic) NSDictionary *semanticContext; // @synthesize semanticContext=_semanticContext;
@property(copy, nonatomic) NSString *identifier; // @synthesize identifier=_identifier;
- (void).cxx_destruct;	// IMP=0x000000010002d8ec
- (id)_firstAvailableChooseActionName;	// IMP=0x000000010002d668
- (_Bool)_isEqualToSiriScreenItem:(id)arg1;	// IMP=0x000000010002d5c4
- (id)_defaultIdentifier;	// IMP=0x000000010002d394
- (id)_defaultSemanticContext;	// IMP=0x000000010002d2f4
- (_Bool)peformActionWithName:(id)arg1 parameters:(id)arg2;	// IMP=0x000000010002d0a0
- (_Bool)isEqual:(id)arg1;	// IMP=0x000000010002ceec
- (id)description;	// IMP=0x000000010002cdf8
- (unsigned long long)hash;	// IMP=0x000000010002cdac
- (id)initWithAccessibilityElement:(id)arg1;	// IMP=0x000000010002cd20

@end

