//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "PBOSSoftwareUpdateProcessDelegate.h"
#import "SSDownloadManagerObserver.h"
#import "SSPurchaseManagerDelegate.h"

@class NSMutableDictionary, NSString, NSTimer, PCSimpleTimer, SSPurchaseManager, TVSBackgroundTask;

@interface PBSoftwareUpdateService : NSObject <SSPurchaseManagerDelegate, SSDownloadManagerObserver, PBOSSoftwareUpdateProcessDelegate>
{
    _Bool _monitoringEnabled;	// 8 = 0x8
    _Bool _presentingAppAlert;	// 9 = 0x9
    double _appSoftwareUpdateCheckTimeIntervalInSeconds;	// 16 = 0x10
    TVSBackgroundTask *_appSoftwareUpdateCheckTask;	// 24 = 0x18
    TVSBackgroundTask *_osSoftwareUpdateInitialCheckTask;	// 32 = 0x20
    TVSBackgroundTask *_osSoftwareUpdatePeriodicCheckTask;	// 40 = 0x28
    PCSimpleTimer *_darkWakeTimer;	// 48 = 0x30
    NSTimer *_vendorBagRefetchTimeoutTimer;	// 56 = 0x38
    double _lastPresentedAppAlertTime;	// 64 = 0x40
    SSPurchaseManager *_purchaseManager;	// 72 = 0x48
    NSMutableDictionary *_operationsByPurchase;	// 80 = 0x50
    NSMutableDictionary *_operationsByDownload;	// 88 = 0x58
}

+ (id)sharedInstance;	// IMP=0x00000001000607bc
@property(readonly, nonatomic) NSMutableDictionary *operationsByDownload; // @synthesize operationsByDownload=_operationsByDownload;
@property(readonly, nonatomic) NSMutableDictionary *operationsByPurchase; // @synthesize operationsByPurchase=_operationsByPurchase;
@property(readonly, nonatomic) SSPurchaseManager *purchaseManager; // @synthesize purchaseManager=_purchaseManager;
@property(nonatomic) double lastPresentedAppAlertTime; // @synthesize lastPresentedAppAlertTime=_lastPresentedAppAlertTime;
@property(nonatomic) _Bool presentingAppAlert; // @synthesize presentingAppAlert=_presentingAppAlert;
@property(nonatomic) __weak NSTimer *vendorBagRefetchTimeoutTimer; // @synthesize vendorBagRefetchTimeoutTimer=_vendorBagRefetchTimeoutTimer;
@property(retain, nonatomic) PCSimpleTimer *darkWakeTimer; // @synthesize darkWakeTimer=_darkWakeTimer;
@property(retain, nonatomic) TVSBackgroundTask *osSoftwareUpdatePeriodicCheckTask; // @synthesize osSoftwareUpdatePeriodicCheckTask=_osSoftwareUpdatePeriodicCheckTask;
@property(retain, nonatomic) TVSBackgroundTask *osSoftwareUpdateInitialCheckTask; // @synthesize osSoftwareUpdateInitialCheckTask=_osSoftwareUpdateInitialCheckTask;
@property(retain, nonatomic) TVSBackgroundTask *appSoftwareUpdateCheckTask; // @synthesize appSoftwareUpdateCheckTask=_appSoftwareUpdateCheckTask;
@property(nonatomic) _Bool monitoringEnabled; // @synthesize monitoringEnabled=_monitoringEnabled;
@property(nonatomic) double appSoftwareUpdateCheckTimeIntervalInSeconds; // @synthesize appSoftwareUpdateCheckTimeIntervalInSeconds=_appSoftwareUpdateCheckTimeIntervalInSeconds;
- (void).cxx_destruct;	// IMP=0x0000000100067f20
- (void)osUpdateProcessDidFinishApplyWithData:(id)arg1;	// IMP=0x00000001000678c0
- (void)osUpdateProcessDidEncounterSlowUpdateWithData:(id)arg1;	// IMP=0x00000001000676e4
- (void)osUpdateProcessDidUpdateApplyProgressWithData:(id)arg1;	// IMP=0x0000000100067468
- (void)osUpdateProcessDidStartApplyWithData:(id)arg1;	// IMP=0x000000010006725c
- (void)osUpdateProcessDidStartRedownloadWithData:(id)arg1;	// IMP=0x00000001000670e4
- (void)osUpdateProcessDidFinishDownloadWithData:(id)arg1;	// IMP=0x0000000100066d4c
- (void)osUpdateProcessDidUpdateDownloadProgressWithData:(id)arg1;	// IMP=0x0000000100066be4
- (void)osUpdateProcessDidStartDownloadWithData:(id)arg1;	// IMP=0x0000000100066a6c
- (void)osUpdateProcessDidFinishCheckWithData:(id)arg1;	// IMP=0x0000000100066604
- (void)osUpdateProcessDidStartCheckWithData:(id)arg1;	// IMP=0x000000010006649c
- (void)downloadManager:(id)arg1 downloadStatesDidChange:(id)arg2;	// IMP=0x00000001000662d8
- (void)purchaseManager:(id)arg1 didFinishPurchasesWithResponses:(id)arg2;	// IMP=0x0000000100065fb0
- (void)_showOSUpdateUpToDateDialog:(_Bool)arg1;	// IMP=0x0000000100065dac
- (void)_showOSUpdateError:(id)arg1 inDomain:(id)arg2 description:(id)arg3;	// IMP=0x0000000100065588
- (void)_showApplyConfirmationDialogWithData:(id)arg1;	// IMP=0x0000000100064eb8
- (void)_showOSUpdateDownloadAndApplyConfirmation:(_Bool)arg1;	// IMP=0x0000000100064b34
- (void)_handleDeviceWillWakeNotification:(id)arg1;	// IMP=0x0000000100064a7c
- (void)_handleDeviceWillSleepNotification:(id)arg1;	// IMP=0x00000001000647e8
- (void)_handleOSUpdatePrefsDidChange;	// IMP=0x00000001000647b0
- (void)_handlePineBoardPrefsDidChange;	// IMP=0x00000001000646e8
- (void)_precheckConditionsAndPerformAction:(unsigned long long)arg1;	// IMP=0x00000001000642d0
- (_Bool)_isAtHomeSeedUser;	// IMP=0x00000001000641b0
- (void)_startOSUpdateCheckForAction:(unsigned long long)arg1;	// IMP=0x00000001000640a8
- (void)_postVendorBagReloadContinueAutoApply;	// IMP=0x00000001000638a8
- (void)_reloadVendorBag;	// IMP=0x000000010006377c
- (void)_osUpdateDarkWakeTimerFired:(id)arg1;	// IMP=0x0000000100063608
- (void)_scheduleOSUpdateDarkWakeAt:(id)arg1;	// IMP=0x0000000100063520
- (void)_cancelOSUpdateDarkWakeTimer;	// IMP=0x00000001000634ac
- (void)_scheduleOSUpdateTimerForNextDarkWake;	// IMP=0x0000000100063208
- (void)_scheduleOSUpdateOnSleepCheck;	// IMP=0x0000000100062f74
- (void)_scheduleOSUpdateCheck;	// IMP=0x0000000100062a94
- (void)_clearFailedDownload:(id)arg1;	// IMP=0x000000010006285c
- (void)_clearDownloadManager:(id)arg1 idleDownloads:(id)arg2;	// IMP=0x000000010006262c
- (void)_handleActiveAccountDidChange;	// IMP=0x00000001000625e8
- (void)_scheduleAppSoftwareUpdateCheck;	// IMP=0x0000000100062130
- (void)addDownload:(id)arg1 forOperation:(id)arg2 completionBlock:(CDUnknownBlockType)arg3;	// IMP=0x0000000100061ccc
- (void)addPurchase:(id)arg1 forOperation:(id)arg2 completionBlock:(CDUnknownBlockType)arg3;	// IMP=0x0000000100061884
- (void)rebootDueToSlowUpdate;	// IMP=0x000000010006183c
- (void)notePlaybackStarted;	// IMP=0x00000001000617f0
- (void)cancelOSSoftwareUpdate;	// IMP=0x00000001000617a4
- (_Bool)isOSSoftwareUpdateRunning;	// IMP=0x0000000100061750
- (void)reallyPerformOSSoftwareRestore;	// IMP=0x0000000100061714
- (void)reallyPerformOSSoftwareUpdateCheck;	// IMP=0x00000001000616d8
- (void)reallyPerformAppSoftwareUpdateCheck;	// IMP=0x0000000100061558
- (void)warnUserOnOutOfSpaceIfNecessary;	// IMP=0x0000000100060e88
- (void)startSoftwareUpdateMonitoring;	// IMP=0x0000000100060bdc
- (id)init;	// IMP=0x0000000100060abc

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

