//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIAlertController.h"

@interface PBSystemMenuViewController : UIAlertController
{
}

+ (_Bool)_systemControlEnabled;	// IMP=0x000000010004fc94
+ (id)systemMenuController;	// IMP=0x000000010004fa88

@end

