//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "TextEntryButtonViewDelegate.h"

@class NSArray, NSMutableArray, NSString, TVSStateMachine, UITapGestureRecognizer;

@interface PBTextEntryViewController : UIViewController <TextEntryButtonViewDelegate>
{
    id <PBTextEntryViewControllerDelegate> _delegate;	// 8 = 0x8
    NSString *_defaultTitle;	// 16 = 0x10
    NSString *_defaultMessage;	// 24 = 0x18
    NSArray *_enteredValues;	// 32 = 0x20
    UIViewController *_childViewController;	// 40 = 0x28
    UITapGestureRecognizer *_menuRecognizer;	// 48 = 0x30
    TVSStateMachine *_stateMachine;	// 56 = 0x38
    long long _currentTextField;	// 64 = 0x40
    NSMutableArray *_textFieldValues;	// 72 = 0x48
    NSMutableArray *_buttonTitles;	// 80 = 0x50
    NSMutableArray *_userValues;	// 88 = 0x58
}

@property(retain, nonatomic) NSMutableArray *userValues; // @synthesize userValues=_userValues;
@property(retain, nonatomic) NSMutableArray *buttonTitles; // @synthesize buttonTitles=_buttonTitles;
@property(retain, nonatomic) NSMutableArray *textFieldValues; // @synthesize textFieldValues=_textFieldValues;
@property(nonatomic) long long currentTextField; // @synthesize currentTextField=_currentTextField;
@property(retain, nonatomic) TVSStateMachine *stateMachine; // @synthesize stateMachine=_stateMachine;
@property(retain, nonatomic) UITapGestureRecognizer *menuRecognizer; // @synthesize menuRecognizer=_menuRecognizer;
@property(retain, nonatomic) UIViewController *childViewController; // @synthesize childViewController=_childViewController;
@property(retain, nonatomic) NSArray *enteredValues; // @synthesize enteredValues=_enteredValues;
@property(copy, nonatomic) NSString *defaultMessage; // @synthesize defaultMessage=_defaultMessage;
@property(copy, nonatomic) NSString *defaultTitle; // @synthesize defaultTitle=_defaultTitle;
@property(nonatomic) __weak id <PBTextEntryViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;	// IMP=0x0000000100057d60
- (id)_messageStringAttributes;	// IMP=0x000000010005795c
- (id)_titleStringAttributes;	// IMP=0x00000001000577dc
- (void)_menuButtonPressed:(id)arg1;	// IMP=0x0000000100057778
- (void)buttonView:(id)arg1 didSelectButton:(id)arg2 atIndex:(long long)arg3;	// IMP=0x00000001000576a0
- (void)_synchronizeEnteredValues;	// IMP=0x0000000100057634
- (id)textField;	// IMP=0x0000000100057598
- (void)_showChildViewController:(id)arg1;	// IMP=0x0000000100057418
- (id)_buttonsForTextField:(long long)arg1;	// IMP=0x00000001000571b8
- (void)_showTextEntryViewControllerForTextField:(long long)arg1;	// IMP=0x0000000100056c90
- (void)_configureStateMachine;	// IMP=0x000000010005656c
- (void)viewDidAppear:(_Bool)arg1;	// IMP=0x0000000100056508
- (void)viewDidLoad;	// IMP=0x00000001000564b4
- (void)loadView;	// IMP=0x000000010005632c
- (unsigned long long)addButtonWithTitle:(id)arg1;	// IMP=0x00000001000562a8
- (void)setAlternateTitle:(id)arg1 message:(id)arg2 forTextFieldAtIndex:(unsigned long long)arg3;	// IMP=0x00000001000561e8
- (unsigned long long)addTextFieldWithInitialText:(id)arg1 placeholder:(id)arg2 keyboardType:(long long)arg3;	// IMP=0x00000001000560a4
- (id)init;	// IMP=0x0000000100056090
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;	// IMP=0x0000000100055f74

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

