//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDictionary, NSString, NSURL, UIViewController;

@protocol PBUIPluginHost <NSObject>
- (void)didChangeMode:(long long)arg1;
- (UIViewController *)presentedViewController;
- (void)dismissViewController:(UIViewController *)arg1;
- (void)presentViewController:(UIViewController *)arg1;
- (void)activateApplication:(NSString *)arg1 openURL:(NSURL *)arg2 options:(NSDictionary *)arg3 completion:(void (^)(_Bool))arg4;
- (void)activateApplication:(NSString *)arg1 openURL:(NSURL *)arg2 completion:(void (^)(_Bool))arg3;
@end

