//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "PBUserNotificationViewController.h"
#import "TVTermsAndConditionsViewDelegate.h"

@class NSString, TVSCFUserNotification, _PBTermsAndConditionsContentView;

@interface PBUserNotificationViewControllerTermsAndConditions : UIViewController <TVTermsAndConditionsViewDelegate, PBUserNotificationViewController>
{
    id <PBUserNotificationViewControllerDelegate> _delegate;	// 8 = 0x8
    TVSCFUserNotification *_notification;	// 16 = 0x10
    _PBTermsAndConditionsContentView *_contentView;	// 24 = 0x18
}

@property(retain, nonatomic) _PBTermsAndConditionsContentView *contentView; // @synthesize contentView=_contentView;
@property(retain, nonatomic) TVSCFUserNotification *notification; // @synthesize notification=_notification;
@property(nonatomic) __weak id <PBUserNotificationViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;	// IMP=0x000000010008aa34
- (void)_handleMenuButton;	// IMP=0x000000010008a904
- (void)termsAndConditionsView:(id)arg1 didSelectButtonAtIndex:(long long)arg2;	// IMP=0x000000010008a8ac
- (void)animateDisappearanceWithCompletion:(CDUnknownBlockType)arg1;	// IMP=0x000000010008a894
- (id)preferredFocusedItem;	// IMP=0x000000010008a494
- (void)viewDidAppear:(_Bool)arg1;	// IMP=0x000000010008a438
- (void)loadView;	// IMP=0x000000010008a2a4
- (id)init;	// IMP=0x000000010008a1e8

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

