//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class NSArray;

@interface PBUserNotificationTextEntryButtonView : UIView
{
    NSArray *_buttonTitles;	// 8 = 0x8
    NSArray *_buttons;	// 16 = 0x10
    id <TextEntryButtonViewDelegate> _delegate;	// 24 = 0x18
}

+ (id)_createButtonsWithTitles:(id)arg1;	// IMP=0x00000001000505fc
@property(nonatomic) __weak id <TextEntryButtonViewDelegate> delegate; // @synthesize delegate=_delegate;
@property(copy, nonatomic) NSArray *buttons; // @synthesize buttons=_buttons;
@property(readonly, copy, nonatomic) NSArray *buttonTitles; // @synthesize buttonTitles=_buttonTitles;
- (void).cxx_destruct;	// IMP=0x00000001000508c4
- (void)_didSelectButton:(id)arg1;	// IMP=0x0000000100050788
- (void)setEnabled:(_Bool)arg1;	// IMP=0x0000000100050564
- (void)layoutSubviews;	// IMP=0x00000001000501d4
- (long long)indexOfButton:(id)arg1;	// IMP=0x0000000100050158
- (id)buttonAtIndex:(long long)arg1;	// IMP=0x00000001000500fc
- (id)buttonWithTitle:(id)arg1;	// IMP=0x000000010004ff44
- (id)initWithButtons:(id)arg1;	// IMP=0x000000010004fd98
- (id)initWithButtonTitles:(id)arg1;	// IMP=0x000000010004fd08

@end

