//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIAlertController.h"

#import "PBUserNotificationViewController.h"

@class NSString, NSTimer, TVSCFUserNotification;

@interface PBUserNotificationBaseViewController : UIAlertController <PBUserNotificationViewController>
{
    NSTimer *_timeoutTimer;	// 8 = 0x8
    TVSCFUserNotification *_notification;	// 16 = 0x10
    id <PBUserNotificationViewControllerDelegate> _delegate;	// 24 = 0x18
}

@property(nonatomic) __weak id <PBUserNotificationViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) TVSCFUserNotification *notification; // @synthesize notification=_notification;
- (void).cxx_destruct;	// IMP=0x00000001000347bc
- (void)_onTimeoutTimer:(id)arg1;	// IMP=0x0000000100034718
- (void)viewDidDisappear:(_Bool)arg1;	// IMP=0x00000001000346b0
- (void)viewDidAppear:(_Bool)arg1;	// IMP=0x0000000100034598
- (void)updateWithNotification:(id)arg1;	// IMP=0x0000000100034594
- (id)init;	// IMP=0x0000000100034470

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

