//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDate, NSUUID, TVSStateMachine;

@interface PBVPNConnection : NSObject
{
    _Bool _wantsToConnect;	// 8 = 0x8
    _Bool _userCanceledConnection;	// 9 = 0x9
    void *_session;	// 16 = 0x10
    NSUUID *_uuid;	// 24 = 0x18
    TVSStateMachine *_stateMachine;	// 32 = 0x20
    CDUnknownBlockType _connectionCompletionBlock;	// 40 = 0x28
    CDUnknownBlockType _disconnectionCompletionBlock;	// 48 = 0x30
    NSDate *_testFetchStartTime;	// 56 = 0x38
    struct __CFUserNotification *_noteRef;	// 64 = 0x40
}

+ (void)cancel;	// IMP=0x0000000100068910
+ (void)disconnectWithCompletion:(CDUnknownBlockType)arg1;	// IMP=0x00000001000687dc
+ (void)connectWithCompletion:(CDUnknownBlockType)arg1;	// IMP=0x0000000100068698
+ (_Bool)isConnecting;	// IMP=0x00000001000685b0
+ (_Bool)isConnected;	// IMP=0x00000001000684f0
+ (_Bool)isValid;	// IMP=0x0000000100068498
+ (id)sharedInstance;	// IMP=0x0000000100068418
@property(nonatomic) _Bool userCanceledConnection; // @synthesize userCanceledConnection=_userCanceledConnection;
@property(nonatomic) struct __CFUserNotification *noteRef; // @synthesize noteRef=_noteRef;
@property(retain, nonatomic) NSDate *testFetchStartTime; // @synthesize testFetchStartTime=_testFetchStartTime;
@property(nonatomic) _Bool wantsToConnect; // @synthesize wantsToConnect=_wantsToConnect;
@property(copy, nonatomic) CDUnknownBlockType disconnectionCompletionBlock; // @synthesize disconnectionCompletionBlock=_disconnectionCompletionBlock;
@property(copy, nonatomic) CDUnknownBlockType connectionCompletionBlock; // @synthesize connectionCompletionBlock=_connectionCompletionBlock;
@property(retain, nonatomic) TVSStateMachine *stateMachine; // @synthesize stateMachine=_stateMachine;
@property(retain, nonatomic) NSUUID *uuid; // @synthesize uuid=_uuid;
- (void).cxx_destruct;	// IMP=0x000000010006d4b8
- (void)_dismissConnectionDialog;	// IMP=0x000000010006d2e0
- (void)_showConnectingDialog;	// IMP=0x000000010006d0d8
- (void)_updateVPNStatus:(int)arg1 forSession:(void *)arg2;	// IMP=0x000000010006ce04
- (void)_stopSession;	// IMP=0x000000010006cdd0
- (void)_startSession;	// IMP=0x000000010006cd9c
- (void)_startTestFetch;	// IMP=0x000000010006c7d8
- (void)_initializeSession;	// IMP=0x000000010006bbcc
- (void)_registerStateHandlers;	// IMP=0x0000000100068a04
@property(nonatomic) void *session; // @synthesize session=_session;
- (id)initForSingleton;	// IMP=0x00000001000681ac
- (id)init;	// IMP=0x0000000100068194

@end

