//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIWindow.h"

#import "UIGestureRecognizerDelegate.h"

@class NSString, TVInteractionGestureRecognizer, UILongPressGestureRecognizer, UITapGestureRecognizer, _UIRepeatingPressGestureRecognizer;

@interface PBWindow : UIWindow <UIGestureRecognizerDelegate>
{
    UILongPressGestureRecognizer *_microphoneLongPressRecognizer;	// 8 = 0x8
    UITapGestureRecognizer *_microphoneTapRecognizer;	// 16 = 0x10
    TVInteractionGestureRecognizer *_microphoneInteractionRecognizer;	// 24 = 0x18
    UILongPressGestureRecognizer *_tvLongPressRecognizer;	// 32 = 0x20
    UITapGestureRecognizer *_tvTapRecognizer;	// 40 = 0x28
    UITapGestureRecognizer *_tvDoubleTapRecognizer;	// 48 = 0x30
    UITapGestureRecognizer *_tvTripleTapRecognizer;	// 56 = 0x38
    UILongPressGestureRecognizer *_rapidVolumeUpRecognizer;	// 64 = 0x40
    UILongPressGestureRecognizer *_rapidVolumeDownRecognizer;	// 72 = 0x48
    UILongPressGestureRecognizer *_longPressMenuRecognizer;	// 80 = 0x50
    UITapGestureRecognizer *_tapMenuRecognizer;	// 88 = 0x58
    UITapGestureRecognizer *_tripleTapMenuRecognizer;	// 96 = 0x60
    UILongPressGestureRecognizer *_playPauseLongPressRecognizer;	// 104 = 0x68
    UILongPressGestureRecognizer *_rewindLongPressRecognizer;	// 112 = 0x70
    UILongPressGestureRecognizer *_fastForwardLongPressRecognizer;	// 120 = 0x78
    UITapGestureRecognizer *_playPauseTapRecognizer;	// 128 = 0x80
    TVInteractionGestureRecognizer *_playTapRecognizer;	// 136 = 0x88
    TVInteractionGestureRecognizer *_pauseTapRecognizer;	// 144 = 0x90
    TVInteractionGestureRecognizer *_stopTapRecognizer;	// 152 = 0x98
    UITapGestureRecognizer *_rewindTapRecognizer;	// 160 = 0xa0
    UITapGestureRecognizer *_fastForwardTapRecognizer;	// 168 = 0xa8
    TVInteractionGestureRecognizer *_nextTrackTapRecognizer;	// 176 = 0xb0
    TVInteractionGestureRecognizer *_previousTrackTapRecognizer;	// 184 = 0xb8
    _UIRepeatingPressGestureRecognizer *_skipForwardsRepeatingPressRecognizer;	// 192 = 0xc0
    _UIRepeatingPressGestureRecognizer *_skipBackwardsRepeatingPressRecognizer;	// 200 = 0xc8
    UITapGestureRecognizer *_selectTapRecognizer;	// 208 = 0xd0
    UITapGestureRecognizer *_directionalRecognizer;	// 216 = 0xd8
    _Bool _acceptsEvents;	// 224 = 0xe0
    NSString *_name;	// 232 = 0xe8
}

@property(readonly, copy, nonatomic) NSString *name; // @synthesize name=_name;
@property(nonatomic) _Bool acceptsEvents; // @synthesize acceptsEvents=_acceptsEvents;
- (void).cxx_destruct;	// IMP=0x000000010003f288
- (_Bool)gestureRecognizer:(id)arg1 shouldRecognizeSimultaneouslyWithGestureRecognizer:(id)arg2;	// IMP=0x000000010003f1b8
- (_Bool)gestureRecognizer:(id)arg1 shouldRequireFailureOfGestureRecognizer:(id)arg2;	// IMP=0x000000010003f0d0
- (id)_newTripleTapGestureRecognizerWithPressTypes:(id)arg1;	// IMP=0x000000010003f014
- (void)setDirectionalGestureRecognizersEnabled:(_Bool)arg1;	// IMP=0x000000010003ee20
- (void)setPlaybackGestureRecognizersEnabled:(_Bool)arg1;	// IMP=0x000000010003e288
- (void)setSelectGestureRecognizersEnabled:(_Bool)arg1;	// IMP=0x000000010003e11c
- (void)setTripleTapMenuGestureRecognizersEnabled:(_Bool)arg1;	// IMP=0x000000010003dfc4
- (void)setMenuGestureRecognizersEnabled:(_Bool)arg1;	// IMP=0x000000010003dcb8
- (void)setMicrophoneGestureRecognizersEnabled:(_Bool)arg1;	// IMP=0x000000010003d900
- (void)setTVGestureRecognizersEnabled:(_Bool)arg1;	// IMP=0x000000010003d484
- (void)setVolumeGestureRecognizersEnabled:(_Bool)arg1;	// IMP=0x000000010003d2ec
- (_Bool)_canBecomeKeyWindow;	// IMP=0x000000010003d290
@property(readonly, copy) NSString *description;
- (id)initWithFrame:(struct CGRect)arg1 name:(id)arg2;	// IMP=0x000000010003d0b8
- (id)initWithCoder:(id)arg1;	// IMP=0x000000010003d098
- (id)initWithFrame:(struct CGRect)arg1;	// IMP=0x000000010003d088

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

