//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "FBProcessManagerObserver.h"
#import "FBSceneManagerObserver.h"
#import "FBSystemServiceDelegate.h"
#import "FBWorkspaceDelegate.h"

@class FBApplicationProcess, FBProcess, FBProcessManager, FBSSystemService, FBSceneManager, FBSystemService, NSArray, NSDictionary, NSMutableOrderedSet, NSMutableSet, NSString;

@interface TVSProcessManager : NSObject <FBProcessManagerObserver, FBSystemServiceDelegate, FBSceneManagerObserver, FBWorkspaceDelegate>
{
    NSMutableOrderedSet *_recentApplicationBundleIdentifiers;	// 8 = 0x8
    NSMutableSet *_activatedApplicationBundleIdentifiers;	// 16 = 0x10
    NSMutableSet *_pendingSceneUpdateTransactions;	// 24 = 0x18
    FBSSystemService *_systemService;	// 32 = 0x20
    FBProcess *_focusedProcess;	// 40 = 0x28
    FBApplicationProcess *_systemWakeTargetProcess;	// 48 = 0x30
    FBSystemService *_fbSystemAppService;	// 56 = 0x38
    FBSceneManager *_fbSceneManager;	// 64 = 0x40
    FBProcessManager *_fbProcessManager;	// 72 = 0x48
    NSMutableSet *_pendingSnapshots;	// 80 = 0x50
    NSString *_kioskApplicationIdentifier;	// 88 = 0x58
    NSDictionary *_appState;	// 96 = 0x60
    NSString *_debuggerTargetBundleIdentifier;	// 104 = 0x68
}

+ (id)_sceneIdentifierForBundleIdentifier:(id)arg1 withDisplay:(id)arg2;	// IMP=0x0000000100099c90
+ (_Bool)automaticallyNotifiesObserversOfFocusedProcess;	// IMP=0x0000000100092954
+ (id)sharedInstance;	// IMP=0x00000001000925a0
+ (void)setupProcessManagementWithRecentApplicationBundleIdentifiers:(id)arg1;	// IMP=0x0000000100092340
+ (void)setupProcessManagement;	// IMP=0x00000001000922ec
@property(copy, nonatomic) NSString *debuggerTargetBundleIdentifier; // @synthesize debuggerTargetBundleIdentifier=_debuggerTargetBundleIdentifier;
@property(copy, nonatomic) NSDictionary *appState; // @synthesize appState=_appState;
@property(copy, nonatomic) NSString *kioskApplicationIdentifier; // @synthesize kioskApplicationIdentifier=_kioskApplicationIdentifier;
- (void).cxx_destruct;	// IMP=0x0000000100099dbc
- (void)_setupEventDeferralsWithScene:(id)arg1;	// IMP=0x000000010009993c
- (void)updateEventDeferrals;	// IMP=0x00000001000998f0
- (id)_foregroundScene;	// IMP=0x0000000100099164
- (_Bool)_scene:(id)arg1 setBackgrounded:(_Bool)arg2 transactionGroup:(id)arg3;	// IMP=0x0000000100098ef8
- (id)_bringApplicationProcessToForeground:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x0000000100098a88
- (void)restoreSystemFromSleepWithCompletion:(CDUnknownBlockType)arg1;	// IMP=0x00000001000989d4
- (void)prepareSystemForSleepWithCompletion:(CDUnknownBlockType)arg1;	// IMP=0x00000001000988ec
- (void)_resetDebuggerTargetBundleIdentifier;	// IMP=0x00000001000988dc
- (void)_reportUntrustedLaunchAttemptWithAppInfo:(id)arg1;	// IMP=0x00000001000983d8
- (void)_appDepotAppStateDidChangeNotification:(id)arg1;	// IMP=0x000000010009835c
- (void)_notePhysicalNetworkStateDidChangeNotification:(id)arg1;	// IMP=0x0000000100098164
- (void)_checkContentRestrictions:(id)arg1 options:(id)arg2 thenProceedWithHandler:(CDUnknownBlockType)arg3;	// IMP=0x0000000100097bac
- (_Bool)_wouldDebuggerTargetPreventLaunchForBundleIdentifier:(id)arg1;	// IMP=0x0000000100097adc
- (_Bool)_applicationSafeForUseOnline:(id)arg1;	// IMP=0x00000001000979d4
- (void)sceneManager:(id)arg1 didDestroyScene:(id)arg2;	// IMP=0x0000000100097988
- (void)sceneManager:(id)arg1 willDestroyScene:(id)arg2;	// IMP=0x0000000100097984
- (void)sceneManager:(id)arg1 didCommitUpdateForScene:(id)arg2 transactionID:(unsigned long long)arg3 success:(_Bool)arg4;	// IMP=0x0000000100097938
- (void)sceneManager:(id)arg1 willCommitUpdateForScene:(id)arg2 transactionID:(unsigned long long)arg3;	// IMP=0x0000000100097934
- (void)sceneManager:(id)arg1 willUpdateScene:(id)arg2 withSettings:(id)arg3 transitionContext:(id)arg4;	// IMP=0x000000010009726c
- (void)sceneManager:(id)arg1 didCreateScene:(id)arg2 withClient:(id)arg3;	// IMP=0x0000000100097268
- (void)workspace:(id)arg1 didReceiveDestroySceneRequestForIdentifier:(id)arg2 withCompletion:(CDUnknownBlockType)arg3;	// IMP=0x0000000100096fd0
- (void)workspace:(id)arg1 didReceiveCreateSceneRequestForIdentifier:(id)arg2 initialClientSettings:(id)arg3 withCompletion:(CDUnknownBlockType)arg4;	// IMP=0x0000000100096af8
- (void)processManager:(id)arg1 didRemoveProcess:(id)arg2;	// IMP=0x0000000100096854
- (void)processManager:(id)arg1 didAddProcess:(id)arg2;	// IMP=0x0000000100096808
- (void)systemServicePrepareForExit:(id)arg1 andRelaunch:(_Bool)arg2;	// IMP=0x00000001000966f0
- (void)systemServicePrepareForShutdown:(id)arg1 withOptions:(unsigned long long)arg2;	// IMP=0x00000001000965d8
- (void)systemService:(id)arg1 handleOpenURLRequest:(id)arg2 application:(id)arg3 options:(id)arg4 origin:(id)arg5 withResult:(CDUnknownBlockType)arg6;	// IMP=0x0000000100096080
- (void)_openApp:(id)arg1 options:(id)arg2 origin:(id)arg3 withResult:(CDUnknownBlockType)arg4;	// IMP=0x00000001000946d0
- (_Bool)_isStorePlaybackURL:(id)arg1;	// IMP=0x000000010009438c
- (void)systemService:(id)arg1 handleOpenApplicationRequest:(id)arg2 options:(id)arg3 origin:(id)arg4 withResult:(CDUnknownBlockType)arg5;	// IMP=0x0000000100093540
- (void)systemService:(id)arg1 canActivateApplication:(id)arg2 withResult:(CDUnknownBlockType)arg3;	// IMP=0x0000000100093334
- (id)mainSceneIDForBundleID:(id)arg1;	// IMP=0x00000001000931f4
@property(readonly, nonatomic) _Bool alternateApplicationIsActive;
- (void)reboot;	// IMP=0x0000000100093144
- (void)relaunch;	// IMP=0x0000000100093128
- (void)sendHIDEventToTopApplication:(struct __IOHIDEvent *)arg1;	// IMP=0x0000000100093120
- (void)killApplication:(id)arg1 removeFromRecents:(_Bool)arg2;	// IMP=0x0000000100092fe4
- (void)activateApplication:(id)arg1 openURL:(id)arg2 options:(id)arg3 suspended:(_Bool)arg4 completion:(CDUnknownBlockType)arg5;	// IMP=0x0000000100092c18
- (void)activateApplication:(id)arg1 openURL:(id)arg2 suspended:(_Bool)arg3 completion:(CDUnknownBlockType)arg4;	// IMP=0x0000000100092b98
- (_Bool)isSiriViewServicePID:(int)arg1;	// IMP=0x0000000100092a4c
- (void)setFocusedProcess:(id)arg1;	// IMP=0x000000010009295c
@property(readonly, nonatomic) FBProcess *focusedProcess;
@property(readonly, copy, nonatomic) NSArray *recentApplicationBundleIdentifiers;
- (void)dealloc;	// IMP=0x0000000100092808
- (id)init;	// IMP=0x00000001000925ac

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

